### ISSUE TITLE
Error not catched, custom adapter

### ISSUE THREAD

**Issue by derpoho** [lexich/redux-api#100]
Hey guys,

can't get my head around this. I created a custom adapter which finishes with an error just in case. The Error is thrown, the fail action is dispatched, but i get a console error that the promise has not been resolved. Am i missing something?

The Adapter
```
export default (fetch) => (url, options) => fetch(url, options)
  .then((resp) => {
    if (resp.status >= 200 && resp.status < 300 && resp.json().success) {
      return resp.json()
    }

    return resp.json()
      .then(json => {
        throw new Error({ status: 400, data: json })
      })
  })

```

This is where stuff is started (rest.js). Nothing more yet.
```
const api = reduxApi({
  authenticate: {
    url: '/authenticate',
    options: {
      method: 'post',
    },
  },
})
.use('fetch', adapterFetch(fetch))
.use('rootUrl', API_BASE)
.use('options', {
  headers: {
    'Accept': 'application/json', // eslint-disable-line
    'Content-Type': 'application/json',
  },
})
```

I don't get it...

**Comment by lexich** [comment]
The main problem is you can call resp.json() only once. It's like stream.

Maybe fix should be looks like:
```js
export default (fetch) => (url, options) => fetch(url, options)
  .then((resp) => {
    if (resp.status >= 200 && resp.status < 300) {
      return resp.json()
    } else {
       Promise.reject(new Error({ status: resp.status, data: "Error" }));
    }
  }).then((json)=> {
    return json.success ? json : Promise.reject(new Error({ status: 400, data: json }));
  });
```

**Comment by lexich** [comment]
Work with fetch API https://developer.mozilla.org/ru/docs/Web/API/Fetch_API/Using_Fetch

**Comment by derpoho** [comment]
Thanks @lexich, i have already found the double .json(). But your thing doesn't solve the problem.
When i reject the promise i get the same error of uncaught errors...

BTW: It doesn't matter which fetch i use. i tried isomorphic, whatwg polyfill and no lib at all... all the same.

**Comment by lexich** [comment]
replace `throw new Error(JSON.stringify(json.error))` with `return Promise.reject(new Error(JSON.stringify(json.error)))`

**Comment by derpoho** [comment]
Already tried that, same error: `actionFn.js:21 Uncaught (in promise) Error:`

I don't get it either. Shouldn`t redux-api catch an errors thrown? Or how do i tell redux-api that this response was an error?

**Comment by lexich** [comment]
@derpoho It's a very interesting question by the way. You way is right to throw error is right. But I think redux-api need to add internal logger system to catch this errors, because unfortunately redux doesn't have this functionality. 
But at this moment, you problem is only error message in console, but wrong response from server is right reason to error message in console.

**Comment by derpoho** [comment]
Your are right @lexich, the problem is only the console message, as i can catch the error through the response. But if you want a clean state in your app, then there shouldn't be this message in the console ;)

F.e. We have error tracking enabled in our app, so once we hit any code greater than 300 in our api we now get two errors thrown in the tracker, one that we submit, and the other one from the unhandled promise. That's not good... ;)

Thanks for taking this in consideration!

**Comment by modosc** [comment]
i'm running into the same issue with a custom adapter, i'd be happy to help with a solution?

**Comment by lexich** [comment]
@derpoho try to update to last version 0.9.10

**Comment by derpoho** [comment]
Done. Nice Job @lexich!
