### ISSUE TITLE
Is there any option to add query params dynamically to action?

### ISSUE THREAD

**Issue by alekbarszczewski** [lexich/redux-api#105]
I have following api definition:
```js
{
  test: { url: '/test', options: { method: 'GET' } },
}
```

And I am calling it like this:

```js
componentDidMount () {
  rest.actions.test({ /* url params*/ }, { /* options */ })
}
```

How I can call `GET /test?key=value`? Is it possible to set querystring / query params in options somehow?

**Comment by lexich** [comment]
Yes, see https://github.com/lexich/redux-api/blob/master/docs/DOCS.md#url-schema last example

**Comment by alekbarszczewski** [comment]
Hey, I managed to do that by wrapping adapterFetch:

```js
/* adapterWithQs.js */

import fetch from 'isomorphic-fetch'
import adapterFetch from "redux-api/lib/adapters/fetch"
import qs from 'qs'

const originalFetchAdapter = adapterFetch(fetch)

export default function adapterWithQs (url, opts) {
  /* modify url with opts.qs */
  if (opts.qs) {
    const queryString = qs.stringify(opts.qs)
    if (queryString) {
      url = `${url}?${queryString}`
    }
  }
  /* call original fetch adapter */
  return originalFetchAdapter(url, opts)
}
```

But it would be nice to have support for query params out of the box (I think it's pretty common usage).

**Comment by alekbarszczewski** [comment]
@lexich Ahhh, that's why I missed it! I've read all the docs but did not expect that query params are passed along with path params :). Thanks!
