### ISSUE TITLE
Server rendering initial data

### ISSUE THREAD

**Issue by hashwin** [lexich/redux-api#106]
Hi @lexich 
I have been using this library for a while now and it works pretty well.
I was wondering if there was a way to set initial data rendered from the server for particular endpoints on initial page load and then have it fetch the regular way when needed after that. This way I don't have to make a bunch of API calls in the beginning, only when required.

**Comment by lexich** [comment]
Hi you should look through [example](https://github.com/lexich/redux-api/tree/master/examples/isomorphic) 

Initial state gets from global variable on [client](https://github.com/lexich/redux-api/blob/master/examples/isomorphic/app/client.jsx#L26-L28) 

Set this variable on server https://github.com/lexich/redux-api/blob/master/examples/isomorphic/app/server.jsx#L60 
https://github.com/lexich/redux-api/blob/master/examples/isomorphic/views/index.ejs#L11

**Comment by lexich** [comment]
Of cause you need fetch all data in Router

https://github.com/lexich/redux-api/blob/master/examples/isomorphic/app/routes/routes.js#L22-L23

**Comment by hashwin** [comment]
Thanks!
