### ISSUE TITLE
Clarify reducer usage

### ISSUE THREAD

**Issue by wvengen** [lexich/redux-api#107]
I've tried to create a custom `reducer` to customize the redux-api object.
After a lot of debugging, I found that my custom reducer is not being called for the redux-api actions for this specific entry. I had expected to be able to catch e.g. `@@redux-api@foo_success` and modify redux-api behaviour a bit (though whether that would happen before or after was unclear to me - now I know it doesn't happen at all).

Suggestion: add to the `reducer` documentation that this is meant (I guess) for custom actions, not for redux-api actions. Did I understand that correctly?

(And I hope this issue helps people looking for this to find an answer more easily already.)

**Comment by lexich** [comment]
Thx @wvengen, It's very important suggestion for documentation improvement.

**Comment by wvengen** [comment]
Wow, thanks :+1: :)
Also kudos to @madhums for helping debugging.
