### ISSUE TITLE
ERR_SPDY_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by deevus** [lexich/redux-api#110]
Hi

I'm trying to integrate `redux-api` into an existing application. When I try to dispatch a `sync` action, I get a `ERR_SPDY_PROTOCOL_ERROR` in the console. 

Any ideas what could be causing this? `fetch` works just fine outside of `redux-api`.

```ts
const headers = {
};

const options = (url, params, getState) => {
  const {user} = getState();
  const accessToken = getAccessToken(user, null);
  return {
    headers: Object.assign({
      "Authorization": `Bearer: ${accessToken}`
    }, headers)
  };
};

const api = reduxApi({
  events: {
    crud: true,
    options,
    url: `${API_URL}/api/Scoring/:fixtureId/Events`,
  }
});

export default api;
```

```ts
const onEnterScoring = (
  nextState: RouterState,
  replace: RedirectFunction,
  dispatch: Dispatch<any>,
  getState: Function,
  callback?: Function
) => {
  const {id} = nextState.params;
  const {events} = scoringApi.actions;
  try {
    events.sync({fixtureId: id})(dispatch, getState, null, callback);
  } catch (e) {
    // do nothing
  }

  callback();
};
```

I can see two dispatched actions in redux. One for the initial request action, then a failed request action.

**Comment by deevus** [comment]
I've also started some TS declarations that you might be interested in as per #93

**Comment by lexich** [comment]
About ERR_SPDY_PROTOCOL_ERROR - for example  https://www.wiknix.com/solved-err_spdy_protocol_error-in-chrome/ I think it's external problem.

About TS - you are welcome, make PR 👍

**Comment by lexich** [comment]
Also you can't try error with try/catch

```js
const onEnterScoring = (
  nextState: RouterState,
  replace: RedirectFunction,
  dispatch: Dispatch<any>,
  getState: Function,
  callback?: Function
) => {
  const {id} = nextState.params;
  const {events} = scoringApi.actions;
  //try {
  const request =
    events.sync({fixtureId: id})(dispatch, getState, null, callback);
  
  // if you want to catch error 
  request.catch((e)=> {
    console.error(e);
  });

  //} catch (e) {
    // do nothing
  //}

  //callback(); - callback should be call by sync
};

```

**Comment by deevus** [comment]
Thanks for the reply.

It also fails in Firefox, so it's not only Chrome. In Firefox, it comes up as "Aborted" in the Firebug net tab. 

Even if it was a browser issue, it can't explain why `fetch` calls outside of `redux-api` are working.

**Comment by lexich** [comment]
Your code looks like working. To understand reasons of error we need to go deeper and need more context. Redux-api makes the same fetch calls.

**Comment by deevus** [comment]
I'm using HTTPS with self-signed certificates. Could that have any bearing?

**Comment by deevus** [comment]
The endpoint I'm calling is also HTTPS.

**Comment by deevus** [comment]
LOL it was a typo

`"Authorization": `Bearer: ${accessToken}``

There should be no `:` after `Bearer`

**Comment by tonytranupc** [comment]
Have you tried this yet?

https://usefulpcguide.com/18302/fix-err_spdy_protocol_error-google-chrome/

Sometimes, the ERR_SPDY_PROTOCOL_ERROR isn't a fault from the server side or come from your script.
