### ISSUE TITLE
Follow up with the PR #112

### ISSUE THREAD

**Issue by Means88** [lexich/redux-api#113]
[Customize prefix in actions type #112](https://github.com/lexich/redux-api/pull/112)
I tried the lasted version and found it not work "sometimes".
**Everything goes well when it works separately, but may not when tow requests come together**
with the example 

``` js
aApi = ReduxApi({ 
  test: { ... },
  ...others
}, { prefix: "a/" });
aAction = aApi.actions

bApi = ReduxApi({ 
  test: { ... },
  ...others 
}, { prefix: "b/" });
bReducer = combineReducers(bApi.reducers);
bAction = bApi.actions

reducer = combineReducers({
  a: ...aApi.reducers, 
  b: bReducer
});

store = createStore(reducer);

console.log("before a");
store.dispatch(aAction.test());
console.log("between a & b");
store.dispatch(bAction.test());
console.log("after b");
```

And I use redux-logger for debug.
The result is

```
before a
action @ ... @@redux-api@a/test
between a & b
after b
...
action @ ... @@redux-api@a/test_success
```

As the state, state.a updated successfully, but nothing was done with state.b
When I dispatch bAction first, It will work as we excepted.
---

I think the reason is here.

``` js
// about line 120 in actionFn.js
const state = getState();
const store = state[reducerName];
const requestOptions = { pathvars, params };
if (store && store.loading) {
  return;
}
```

The `reducerName` is the same, and `state` is the top-level redux state( right? ), so the request from b was rejected by it. 

``` js
state: {
  test: {  loading: true } // rejected
  b: {  test: {  loading: false  }  }
}
```

But when we dispatch bAction first, it won't reject request from a.

``` js
state: {
  test: {  loading: false } // OK
  b: {  test: {  loading: true  }  }
}
```

**Comment by lexich** [comment]
Yes, there is a problem at this moment. Redux-api doesn't tested in multi-instance mode yet. If you want you can try to solve this problem by your-self or waiting me when I'll had free time to make research.

**Comment by Means88** [comment]
OK, I'll make a PR if I find a solution.

**Comment by lexich** [comment]
@Means88 I try ti fix your problem. Can you update to 0.9.14 and check?

https://github.com/lexich/redux-api/blob/master/docs/Scoping.md
https://github.com/lexich/redux-api/commit/7fba9b1ac9e6cb0e4f0defdf352cae035e466dcc

**Comment by Means88** [comment]
Yes! It works well. Thanks very much!
