### ISSUE TITLE
crud post helper overwrites state data

### ISSUE THREAD

**Issue by deevus** [lexich/redux-api#114]
If I set `crud: true` for an API endpoint, and call `post(...)`. The state tree is replaced with the return value of the success action. 

The restful way is to return the updated/new objects only, not the entire list of objects. So I should be able to have redux-api concat the returned data into the state tree. 

Having to subsequently call `sync()` means an unwanted redraw when the initial state tree is overwritten with the updated objects returned from `post(...)`.

**Comment by deevus** [comment]
I think essentially the problem is that redux-api doesn't properly handle the result of any of the crud helper methods. 

However, I think it is more complicated than that. In my case I'm using the state tree to render a list of items. They can be created, updated or deleted. 

- When I `post` to create an item, I would like the return value to be appended to the state, not replace.
- When I `delete` an item, I would like that item to be removed from the state tree
- When I `post` to update an item, I want the item in the state tree to be updated. 

I'm not too sure how to achieve this with `redux-api`

**Comment by deevus** [comment]
I have been able to "solve" this by returning the new list of items with every request, but I find that overkill. 

http://www.restapitutorial.com/lessons/httpmethods.html

**Comment by Means88** [comment]
You can just customize the adapter, and maintain the state as you wish.

**Comment by lexich** [comment]
@deevus You can write something like this
```js
const rest = reduxApi({
   todos: {
      url: "/api/v1/todo/list",
      reducer(state, action) {
         if (action.type === "UPDATE_LIST") {
             return state.data.concat(action.data)
         }
         return state;
      }
   },
   todo: {
      url: "/api/v1/todo/:id",
      postfetch: [
        function({data, request, dispatch}) {
            if (request.method === "post") {
               dispatch({type: "UPDATE_LIST", data });
            }
            // .....
        }
      ]
   }
})
```

**Comment by jimbofreedman** [comment]
Are you using immutable state? I've had issues with the state not being fetched in to the transformer because of that.

**Comment by lexich** [comment]
Yes, but my code has mistake
```js
return { ...state, data: state.data.concat(action.data) }
```
It's only update another reducer (todos) with action for (todo) reducer.
Redux-api plays by the redux rules
