### ISSUE TITLE
responseHandler never called

### ISSUE THREAD

**Issue by lvauvillier** [lexich/redux-api#117]
I'm trying to make response handler working.

From the doc, i simply add this to my redux-api setup:

    reduxApi({ ... }).use("responseHandler",
      (err, data)=>
        err ? console.log("ERROR", err) : console.log("SUCCESS", data));

But the function is never called.

It seems that the following line is wrong:
https://github.com/lexich/redux-api/blob/master/src/actionFn.js#L61
(at this point, the meta object is at it's initial state)

I make it working moving this line in the request function:

    const request = (pathvars, params, getState=none)=> {
        const responseHandler = meta && meta.holder && meta.holder.responseHandler;
        const resultUrlT = urlTransform(url, pathvars, meta.urlOptions);
        const rootUrl = meta.holder ? meta.holder.rootUrl : null;
        ...
    }

If this is the right way to fix the problem, I can make a PR.

**Comment by lexich** [comment]
Yes. You are right. It's a mistake. responseHandler can be initialized after create redux-api schema. This line should be under request function. Of caurse I'll be great if you make PR with tests.

**Comment by lvauvillier** [comment]
PR done with tests

**Comment by lvauvillier** [comment]
Thanks
