### ISSUE TITLE
adding cookie to request

### ISSUE THREAD

**Issue by ShayMatasaro** [lexich/redux-api#121]
Hi,

What is the best way to add  cookie data  to the request?

**Comment by ShayMatasaro** [comment]
solved using : 

export  const api = reduxApi({    
    ajax1: {
        url : '/ajax/.ajax.json',
        options:{
            credentials: 'same-origin',
        }
    },

**Comment by int-index** [comment]
@ShayMatasaro Thank you for posting the solution, it helped me.
