### ISSUE TITLE
Include Axios as adapter

### ISSUE THREAD

**Issue by EduardoAC** [lexich/redux-api#123]
Redux-api is a great and easy to use library and I want to contribute to do even better. 

I would like to add as part of this library Axios as adapter to handle the request instead of ```isomorphic-fetch```.

I started to create the adapter but I want to know what else are the areas that it will impact this change in case i missing something.

**Comment by lexich** [comment]
Hi @EduardoAC . New adapter is great idea. You are welcome. The main idea of adapters that they are pluggable and `isomorphic-fetch` is convenient way to use it on server and client, but it's not only one way.

**Comment by EduardoAC** [comment]
I already created the adapter. However I am not sure if you pass the method of the request on get, post, put and delete so I can reuse the logic

**Comment by EduardoAC** [comment]
Ok, @lexich The adapter work but you need to pass the method from the core in order to execute the rest calls. Do you mind if I put in placed a solution on the core of the application? Or should I keep it in the adapter?

**Comment by lexich** [comment]
Separated adapter will be better, anyway make you sould make PR.

**Comment by EduardoAC** [comment]
Thanks for closing it. I am using a separate adapter without any problem, this API is really extensible, I love it. I forgot about the PR

**Comment by lexich** [comment]
👍
