### ISSUE TITLE
[Question] array parameters in URL

### ISSUE THREAD

**Issue by shirbr510** [lexich/redux-api#139]
my api recieves arrays from urls as following

`?cars[]=Saab&cars[]=Audi&cars[]=Toyota`

the server will recieve the data as a param called `cars` with the value `["Saab", "Audi", "Toyota"]`

a. is this format supported?
b. does `redux-api` support arrays via URL?

**Comment by lexich** [comment]
@shirbr510 Hello. Yes this format supported.
```js
const rest = reduxApi({
   cars: {
      url: "/api/cars",
      urlOptions: { arrayFormat: "repeat", delimiter: "&" }
   }
});

rest.actions.cars({ cars: ["Saab", "Audi", "Toyota"] })
```

**Comment by shirbr510** [comment]
@lexich thanks for the quick answer!

just to make sure I understand correctly:

if I'm configuring as you suggested, then the request being made should look like:

`http://<some-domain>/api/cars?cars[]=Saab&cars[]=Audi&cars[]=Toyota`

**Comment by shirbr510** [comment]
@lexich I've just tried it and it works great!
thank you so much! 👍
