### ISSUE TITLE
Unable to call a redux-api action concurrently

### ISSUE THREAD

**Issue by binhqd** [lexich/redux-api#141]
I'm trying to call a redux-api action concurrently but it only serving first call even each request has different parameters or data.

I'm trying to check the source code and I think this prevent me from doing concurrent call: https://github.com/lexich/redux-api/blob/master/src/actionFn.js#L134

Is there a way that I can do these call?

**Comment by lexich** [comment]
Hi. It's wrong way to update store concurrently and this is cause why this behaviour doesn't allow. But if you want to make only request without update store you should use `request` helper https://github.com/lexich/redux-api/blob/master/src/actionFn.js#L199

https://github.com/lexich/redux-api/blob/master/docs/DOCS.md#request

**Comment by binhqd** [comment]
Thank @lexich ,
`request` may help
