### ISSUE TITLE
[Question] CRUD helpers

### ISSUE THREAD

**Issue by divan** [lexich/redux-api#147]
Hi,

I'm currently using `crud: true` option for some of the endpoints. Backend expects requests to be in the following format:

1 `GET /users` - list all users
2 `GET /users/1` - return info on user with id 1
3 `POST /users` - create new user
4 `PUT /users` - change user
5 `DELETE /users/1` - delete user with id 1.

Currently, if endpoint defined as:
``` users: { url: `/users`, crud: true, transformer: transformers.array },```

I have properly working requests 1,3 and 4.
2 and 5 sends id as a url param - `GET /users?id=1`.

Is it possible to implement format described above in a single endpoint definition? If it can be achieved with helpers, is there a way to write the one helper for all endpoints (I do have a lot of similar ones)?

Thanks in advance.

**Comment by lexich** [comment]
Yes, rewrite it with [helpers](https://github.com/lexich/redux-api/blob/master/docs/DOCS.md#helpers)

{ crud: true, { get: (....){}, delete(...){}}}

**Comment by divan** [comment]
@lexich thanks, but what should be in the helper?

I tried:
```users: { url: `/api/users`, crud: true, get(id) { return [{}, {id}] }, transformer: transformers.array },```

**Comment by lexich** [comment]
You have little mistake. Check this test https://github.com/lexich/redux-api/commit/c98bf2cffeb66b63501e97aed31c142ef9a5e7bb It helps you @divan

**Comment by hsingh23** [comment]
@divan your url should be url: `/users/:id`
