### ISSUE TITLE
Set {mode:'no-cors'} in fetch

### ISSUE THREAD

**Issue by vuhaininh** [lexich/redux-api#151]
Hi, how can I set {mode:'no-cors'} in fetch because I have problem with CORS

"FETCH API cannot load
 No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

Thanks

**Comment by lexich** [comment]
Hi. Use https://github.com/lexich/redux-api/blob/master/docs/DOCS.md#options for each endpoint or global interceptor for all endpoints https://github.com/lexich/redux-api/blob/master/docs/DOCS.md#options-1

**Comment by vuhaininh** [comment]
Hi,
I set:  options: {
   mode: 'no-cors'
}
the fetch is completed but I do not get data in actions / reducers
Could you please fetch Data from this:

```
`${YLE_URL}items.json?q=finland&mediaobject=${MEDIA_TYPE}&app_id=${APP_ID}&app_key=${APP_KEY}`

const YLE_URL = `https://external.api.yle.fi/v1/programs/`;
const APP_ID = '7d027e13';
const APP_KEY = '88e86f19ddfcb0ee4f0a996fc74d8658';
const MEDIA_TYPE = 'audio';

```
My code is:
``
export default reduxApi({
    audios: {
      url: `${CORS_URL}${YLE_URL}items.json?q=:term&mediaobject=${MEDIA_TYPE}&app_id=${APP_ID}&app_key=${APP_KEY}`,
      broadcast: [SELECT_FIRST_AUDIO],
      options: {
        mode: 'no-cors'
      }
    }

}).use("fetch",adapterFetch(fetch));

**Comment by lexich** [comment]
When I do the same in console `fetch(url, { mode: 'no-cors' })` I have error:
`Refused to connect to 'https://external.api.yle.fi/v1/programs/items.json?q=finland&mediaobject=audio&app_id=7d027e13&app_key=88e86f19ddfcb0ee4f0a996fc74d8658' because it violates the document's Content Security Policy`.
Redux api is only lightweight wrapper above fetch api and redux. Pls write you workable code with fetch and i help you implement it. But you example above looks correct

**Comment by vuhaininh** [comment]
Hi I run the following code in console and it works. Could you please check again.

`fetch("https://external.api.yle.fi/v1/programs/items.json?q=finland&mediaobject=audio&app_id=7d027e13&app_key=88e86f19ddfcb0ee4f0a996fc74d8658",{mode: 'no-cors'})`

When I used  options mode no-cors in redux-api, it can fetch but it does not return data to state.audios  ( null )

**Comment by vuhaininh** [comment]
I open a new blank tab in Chrome to run the code
`fetch("https://external.api.yle.fi/v1/programs/items.json?q=finland&mediaobject=audio&app_id=7d027e13&app_key=88e86f19ddfcb0ee4f0a996fc74d8658",{mode: 'no-cors'})`

**Comment by lexich** [comment]
Try this. `fetch("https://external.api.yle.fi/v1/programs/items.json?q=finland&mediaobject=audio&app_id=7d027e13&app_key=88e86f19ddfcb0ee4f0a996fc74d8658",{mode: 'no-cors'}).then(d => d.text()).then(d => console.log("Done", d)).catch(err => console.error("Error", err))` Response body is empty.

**Comment by vuhaininh** [comment]
Ok I see that. 
So I am confusing how I can do to get  data from that api

**Comment by Kolyasya** [comment]
I have the same problem. If I have no `{ mode: 'no-cors' }` setting and use [Chrome CORS Extension](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi) I have my data with no problems.
When I switch `{ mode: 'no-cors' }` and disable CORS Extension I have a successful request and it seems like it receives the data, but I have nothing in my Redux Store.

![image](https://user-images.githubusercontent.com/3371143/31288072-26ebe49e-aacc-11e7-91c1-b273f6911889.png)

**Comment by lexich** [comment]
Hi @Kolyasya There is no any content in your response. ![image](https://user-images.githubusercontent.com/3371143/31288724-cc8dd32e-aace-11e7-990e-0b37dce321cb.png)
