### ISSUE TITLE
Inconsitency between `prefetch` and `postfetch`

### ISSUE THREAD

**Issue by xurei** [lexich/redux-api#154]
In the arguments :
- prefetch : requestOptions
- postfetch : request

Both contain the same data. Wouldn't it be more convenient to give them the same name ?

**Comment by xurei** [comment]
(For backward-compatibility, the renamed could stay with a warning telling to migrate...)

**Comment by lexich** [comment]
Yes, I think that it's good point.

**Comment by lexich** [comment]
Inconsitency was fixed in version v0.10.8
