### ISSUE TITLE
Write to state on request action

### ISSUE THREAD

**Issue by jakeaaron** [lexich/redux-api#155]
Hello,

I use the transformer to manipulate the response and then write to state, but how could i also write to state on the request action rather than only the success action?

thank you!

**Comment by lexich** [comment]
Hello @jakeaaron .
At this moment you can define global [responseHandler](https://github.com/lexich/redux-api/blob/master/docs/DOCS.md#responsehandler) and transform error request to success.

**Comment by jakeaaron** [comment]
ok thanks!
