### ISSUE TITLE
[How To] Wait for get response

### ISSUE THREAD

**Issue by EduardoAC** [lexich/redux-api#156]
Hi 

My current scenario: I need to response of an `api.data.get` in order to be able to trigger a new update by using `.put`

I want to update the status property of my profile object. In order to do that I need:
1. Fetch the existing data for the profile (using the id)
2. Update the variable `status`
3. Put the data to the backend to be update it.

Is any way to do that without build my own custom logic?

**Comment by lexich** [comment]
Hi @EduardoAC As I understand you right, you need write something like this.
```js
reduxApi({
   data: {
      url: '/api/v1/data',
      crud: true,
      helpers: {
         modifyApi(id) {
            const { dispatch, actions } = this;
            return (cb) => {
              dispatch(actions.data.get(id)).then((data)=> {
                   data.status = "OK";
                   dispatch(actions.data.put(id, data));
              }).then(d => cb(null, data), cb);
            }
         }
      }
   }
})
// using
dispatch(rest.data.modifyApi(123));
```

**Comment by EduardoAC** [comment]
That's exactly what I need.

Thanks
