### ISSUE TITLE
Typical usage

### ISSUE THREAD

**Issue by dagda1** [lexich/redux-api#160]
I am still unclear how redux-api should be used from the docs:

If I have a rest object like this

```
export default reduxApi({
  getCountries: {
    url: `/countries`,
    transformer(data) {
      const d = fromJS(data);
      return d;
    }
  }
}).use('options', (url, params, getState) => {
  const headers = {
    Accept: 'application/json',
    'Content-Type': 'application/json'
  };

  return { headers };
});
```

What happens with the result?  How do I get the data into the global sate.  I can see some sort of name spaced action is raised:

`@@redux-api@getCountries_success`

Should I have case in a switch statement to test for this.

I'm confused what happens after the asyn call returns

**Comment by dagda1** [comment]
Also when I import the above reduxApi object

`
import reduxApi from './rest';

console.log(reduxApi.reducers); // {}
`

Returns an empty hash, I take it, it should return an actual object?

**Comment by lexich** [comment]
> What happens with the result?

State should be looks like:
```js
{
   getCountries: {
       sync: true,
       syncing: false,
       loading: false,
       pathvars: {},
       body: {},
       data: ImmutableObject,
       error: null
   }
}
```
> How do I get the data into the global state.

It's only redux wrapper which generate [actions](http://redux.js.org/docs/basics/Actions.html) and [reducers](http://redux.js.org/docs/basics/Reducers.html). All data persists in [store](http://redux.js.org/docs/basics/Store.html).

**Comment by lexich** [comment]
Check typical usage in [examples](https://github.com/lexich/redux-api/blob/master/examples)

**Comment by EduardoAC** [comment]
I will try to help as well:
> What happens with the result? How do I get the data into the global sate

The truth is that redux api push the data directly to the state of your redux application by using the path defined in the object passed to `reduxApi()` function. 

Which means that the data will store in the variable call `getCountries` as object that will contain the information above mention.

In order to use in your component you will need to use `mapStateToProps` from `connect` something like

```
const mapStateToProps = state => ({
  countries: state.getCountries 
});

const mapDispatchToProps = dispatch => ({
  getCountries: () => dispatch(api.actions.getCountries()),
});

export default connect(mapStateToProps, mapDispatchToProps)(CountriesComponent);
```

**Comment by dagda1** [comment]
Hi,

Thank you for the answers, I have removed immutabljs.

I have a `redux-api` object like this:

import reduxApi from 'redux-api';
```
export default reduxApi({
  countries: {
    reducerName: 'global',
    url: `/countries`
  }
});
```
And my component looks like this now:

```
class Application extends Component {
  componentWillMount() {
    this.props.dispatch(actions.countries());
  }
}

function select(state) {
  console.log(state);
  return { countries: state.countries };
}

export default connect(select)(Application);
```

Everything seems to go through ok and I can see the following redux-logger message:

`@@redux-api@countries_success`

But my global state object looks like this:
```
{ application: {}, form: {}}
```

The countries is not in the global state?

Am I missing something?

**Comment by dagda1** [comment]
Actually the problem was my reducer, changing it to this fixed my problem:

```
export default function createReducer(asyncReducers) {
  return combineReducers({
    form,
    application: applicantReducer,
    api: combineReducers(reduxApi.reducers)
  });
}
```

Calling `combineReducers` on the `reduxApi.reducers` was the missing bit for me.
