### ISSUE TITLE
testing redux-api

### ISSUE THREAD

**Issue by dagda1** [lexich/redux-api#161]
What are the strategies for testing `redux-api`?

Are there any example? 

is it a matter of mocking isomorphic-fetch with something like `fetch-mock`?

**Comment by lexich** [comment]
`redux-api` basically is generator of actions and reducers. They are aiming to be pure functions. And all tests keep it in mind and test `input` => `output` and may be middlewares calls. Examples are [here](https://github.com/lexich/redux-api/tree/master/test) And tests with redux environment are [here](https://github.com/lexich/redux-api/blob/master/test/redux_spec.js)

**Comment by dagda1** [comment]
What I mean is, say for example, I have a component that is calling an action:
```
class Application extends Component {
  componentWillMount() {
    this.props.dispatch(actions.countries());
  }
```

I want to write an integration test that checks that if everything is wired up correctly then I will have a select full of countries:
```

  it('should resort country list from API', () => {
    const wrapper = testUtils.wrapComponentInReduxForTesting(PlaceOfBirth);

    const select = wrapper.find('option').at(1);

    expect(select.text()).toBe('United Kingdom');
  });
``` 

There are no hooks that I know of in `redux-api` to let me mock the api response that will come back.

The only thing I can think of is `fetch-mock`, something like:

```
  beforeEach(() => {
    fetchMock.get('/countries', [
      { id: 'UNITED_KINGDOM', displayName: 'United Kingdom' }
    ]);
  });
```

But this is not working.  I am using jest and jsdom.  Does `redux-api` rely on fetch being on the window object?

There is no window object in `jsdom`.

**Comment by lexich** [comment]
Or I understand you. it's very simple to mock requests. You should write your custom fetch adapter.
 It's very thin wrapper around [fetch adapter](https://github.com/lexich/redux-api/blob/master/src/adapters/fetch.js) . 

```js
rest.use("fetch", customAdapter);
```

**Comment by dagda1** [comment]
So I have my `restApi` like this:

```
function mockFetchAdapter() {
  return (url, opts) => {
    console.log('********');
  };
}

export default reduxApi({
  countries: {
    url: `/countries`,
    transformer(data) {
      // do stuff

      return transformers.array(resorted);
    }
  }
}).use('fetch', mockFetchAdapter);
```
But I can see   line executes before 
 this [line](https://github.com/lexich/redux-api/blob/823e101cda5e95373f7da767433d9cf2e3dbf4fb/src/index.js#L115) before this [line](https://github.com/lexich/redux-api/blob/823e101cda5e95373f7da767433d9cf2e3dbf4fb/src/index.js#L72) and so the custom fetch is set too late.

Is this a bug?

**Comment by dagda1** [comment]
It works if I use it like this:
```
export default reduxApi({
  countries: {
    url: `/countries`,
    transformer(data) {
      // do stuff

      return transformers.array(resorted);
    },
    fetch() {
      // custom fetch
    }
  }

**Comment by lexich** [comment]
@dagda1 You have little error. Second argument should be function like `(url, opt) =>`
```js
}).use('fetch', mockFetchAdapter()); 
```
