### ISSUE TITLE
'this' context is undefined in reducer

### ISSUE THREAD

**Issue by jakeaaron** [lexich/redux-api#167]
I'm trying to listen to other endpoint actions in one specific endpoint's reducer by using `this.events`,
but `this` is undefined.

```javascript
reducer: (state, action) => {
	console.log('REDUCER', this) // this is undefined
	return state
}
```

**Comment by lexich** [comment]
Hi. If you want to use context, arrow function isn't your choice. 
Use `reducer(state, action){ ... }`

**Comment by jakeaaron** [comment]
oh, I see! thanks a lot!
