### ISSUE TITLE
sync() not working

### ISSUE THREAD

**Issue by cristianfraser** [lexich/redux-api#168]
I'm trying to use the `sync()` method as shown in the [docs](https://github.com/lexich/redux-api/blob/master/docs/DOCS.md#syncurlparams-params-callback), but even though my `sync` flag is set to `true`, the request is made.

My code is as follows:

```
import clientsApi from 'api/clients';

componentDidMount() {
  this.props.fetchClientInfoSync({ clientId: this.props.id });
}

const mapDispatchToProps = dispatch => ({
  fetchClientInfoSync: (...args) => dispatch(clientsApi.actions.config.sync(...args)),
});
```

Every time the component is mounted, the api call is made, even when it's being called with `sync()`

Is this the way it's supposed to be used, is it my mistake or a bug?

**Comment by lexich** [comment]
Hi. Looks good. How do you define endpoint config?

**Comment by cristianfraser** [comment]
Hey, my endpoint is like this:

```
config: {
  url: 'api/v1/config/:clientId/',
  transformer: transformers.client.config,
  options: {
    credentials: 'same-origin',
    method: 'GET',
  },
},
```

**Comment by lexich** [comment]
Try to debug at this place https://github.com/lexich/redux-api/blob/master/src/actionFn.js#L270

**Comment by cristianfraser** [comment]
I just checked, and `store` is `undefined`. Looking the lines just above, shouldn't it be `state.api[name]` instead of `state[name]`? `state` is my whole redux state, so `redux-api` state is inside `state.api`.

**Comment by lexich** [comment]
Read https://github.com/lexich/redux-api/blob/master/docs/Scoping.md 

As I understand in your configuration you should use prefix `api`

**Comment by cristianfraser** [comment]
How's that? I am using that prefix. So `state` in that code line is 

```
state: {
  api: { ... },
  sth: { ... },
}
```

And `name` is `' config'`, so `state[config] = undefined`, because it isn't there. `state.api[config]` is there.

**Comment by lexich** [comment]
Write pls how you connect reducers to redux

**Comment by cristianfraser** [comment]
```
import clientsApi from 'api/clients';

export default combineReducers({
  api: combineReducers({
    clients: combineReducers(clientsApi.reducers),
  }),
```

`clientsApi` is where my endpoints are configured with `reduxApi()`.

**Comment by lexich** [comment]
According https://github.com/lexich/redux-api/blob/master/docs/Scoping.md
Your clientsApi should be defined as
```js
const clientsApi = reduxApi({...},{ prefix: "api"})
```

I think you problem is here.

**Comment by cristianfraser** [comment]
Oh yikes! I was getting things totally wrong. No idea where I got the default `prefix` was `api` from. I'll try this and let you know.

**Comment by cristianfraser** [comment]
So... still have the same problem. If my reducers are like I said above:

```
import clientsApi from 'api/clients';

export default combineReducers({
  api: combineReducers({
    clients: combineReducers(clientsApi.reducers),
  }),
```

Should the prefix be `{ prefix: 'api' }`? The docs example is:

```
const reducer = combineReducers({
  r1: combineReducers(rest1.reducers), // <-- the same scope (r1)
  r2: combineReducers(rest2.reducers), // <-- as in prefix   (r2)
  r3: combineReducers(myReducers)
});
```

In this case the prefixes are `r1` and `r2`. But in my case I have ` { api: { clients, other } }` so the prefix should be something like `{ prefix: { api : 'clients' } }`, but that isn't supported?

Am I reading it right?

**Comment by lexich** [comment]
Yes, not supporting. You should simplify your reducer nesting.

**Comment by cristianfraser** [comment]
Ok, I'm closing this then.

Any chance this could be implemented in the future?

**Comment by lexich** [comment]
I think that it's not popular problem, but if you want to make PR it will be cool
