### ISSUE TITLE
Cache not working

### ISSUE THREAD

**Issue by hartantothio** [lexich/redux-api#170]
There doesn't seem to have sufficient documentation or working examples where "cache" option is used? I tried this in my application, but I can still see network request being fired even after setting "cache: true".

One thing I notice in the console panel is that I see the action being logged, namely "@@redux-api@branchList_cache". Anybody was able to get this working?

**Comment by lexich** [comment]
Hello @hartantothio. Show your rest-api configuration and how do you use it.

**Comment by hartantothio** [comment]
Sorry for late response. I was debugging. Seems like my issue relates to scoping. I was able to fix it.

Thanks
