### ISSUE TITLE
Proper way to combine redux-api and other reducers?

### ISSUE THREAD

**Issue by adamdonahue** [lexich/redux-api#174]
Is there a means by which one can specify a custom reducer path for redux-api, rather than defaulting to the top level?

For example, if I want my state to look like this:

```javascript
const initialState = {
    rest: combineReducers(rest.reducers),
    otherState: {}
};
```

So instead of looking for `users` at the top level of the state tree, redux-api will look at rest.users.  Or other ways to avoid name clashes.

**Comment by lexich** [comment]
Hi @adamdonahue Do you read [Scoping](https://github.com/lexich/redux-api/blob/master/docs/Scoping.md)? Can it be answer to your question?

**Comment by adamdonahue** [comment]
This is fine, thanks.  Also thought we could map to a distinct top-level reducer key if necessary (e.g., REST_users).

**Comment by adamdonahue** [comment]
By the way, great stuff.
