### ISSUE TITLE
Problems using PUT with fetch api with and without CRUD

### ISSUE THREAD

**Issue by EduardoAC** [lexich/redux-api#176]
Hi Guys,

I am having problems to PUT data into the backend using fetch adapter. Instead of fire a PUT request is sending a OPTIONS request without body. What am I doing wrong?

```
import reduxApi, { transformers } from 'redux-api';
import adapterFetch from 'redux-api/lib/adapters/fetch';

const headers = {};
const URL = 'http://localhost:3000';

export default reduxApi({
  survey: {
    url: `${URL}/surveys/:id`,
    transformer: transformers.object,
    crud: true,
  }
}).use('options', () => ({
  headers,
})).use('fetch', adapterFetch(fetch));
```

my dispatch in my component is 
```
(id, values) => dispatch(api.actions.survey.put(
    { id },
    { body: values },
))
```
Resques done by redux-api (POST is working fine)
```
Request URL:http://localhost:3000/surveys/1
Request Method:OPTIONS
Status Code:204 No Content
Remote Address:127.0.0.1:3000
Referrer Policy:no-referrer-when-downgrade
```
I am not using the library isomorphic-fetch.

Any thoughts what could it be?

**Comment by EduardoAC** [comment]
I overcome the problem to be able to PUT data into my endpoint.

First, all the data send by PUT need to be passed through `JSON.stringify` and attach to an object with the property `{ body: {content}` which is not really intuitive of describe on the documentation.

Second the PUT call happen through the network tab from chrome uses `JSON` as a type of the request instead of `XHR` plus a pre-call to options for some reason to the server. Which doesn't happen with the `POST` requests. 

Any ideas why the fetch API behaves so different compare with Axios or Ajax?

**Comment by lexich** [comment]
Hi @EduardoAC redux-api it's only wrapper. You can write you own adapter for Axios or Ajax or plain xmlhttprequest etc. Redux-api describe schema of communication with data-source. Default way is using fetch, but it's not necessary.

**Comment by EduardoAC** [comment]
@lexich I understand and I solved my issue but I was curious if you knew why this multiples request happened
