### ISSUE TITLE
How submit body in a POST action?

### ISSUE THREAD

**Issue by tomsoderlund** [lexich/redux-api#179]
I’m using [`crud: true` to set up CRUD actions automatically](https://github.com/lexich/redux-api/blob/master/docs/DOCS.md#crud). But how do I do a POST action?

When I try:

	this.props.dispatch(reduxApi.actions.blogPosts.post({ }, { body: JSON.stringify(newBlogPostObject) }));

...`body` is empty when it hits the server.

**Comment by lexich** [comment]
Hi @tomsoderlund 
Show your redux-api config.
Are you sure that `newBlogPostObject` has data?

**Comment by tomsoderlund** [comment]
Hi @lexich, here is from my `reduxApi.js`:

	export default reduxApi({

		// Complex endpoint description
		blogPosts: {
			url: 'http://localhost:3014/api/posts/:id',
			crud: true,
			transformer: transformers.array
		}

	}).use('fetch', adapterFetch(fetch));

Here's the event that creates `newBlogPostObject`:

	handleAdd (event) {
		const newBlogPostObject = {
			name: this.state.name,
		};

		const updateLocalBlogPostState = function (err, results) {
			console.log('POST 2', err, results);
		};

		console.log('POST 1', newBlogPostObject);
		this.props.dispatch(reduxApi.actions.blogPosts.post({}, { body: JSON.stringify(newBlogPostObject) }, updateLocalBlogPostState));
	}

With the 'POST 1' log statement, I see that `newBlogPostObject` indeed has data.

**Comment by tomsoderlund** [comment]
P.S. is `JSON.stringify` necessary?

**Comment by tomsoderlund** [comment]
The issue was missing `"Content-Type": "application/json"` in reduxApi:

	options: {
		headers: {
			'Accept': 'application/json',
			'Content-Type': 'application/json'
		}
	}

**Comment by lexich** [comment]
👍
