### ISSUE TITLE
How can I use dispatch in responseHandler?

### ISSUE THREAD

**Issue by pohodnya** [lexich/redux-api#181]
```javascript
api.use("responseHandler", (err, data) => {
  if (err) {
    dispatch(connectionErrorActions.show());
  } else {
    return data;
  }
});
```

Can you add `getState` and `dispatch` as params to callback?

**Comment by lexich** [comment]
Hi @pohodnya check this issue https://github.com/lexich/redux-api/issues/172

**Comment by pohodnya** [comment]
@lexich,
```javascript
const reducer = combineReducers(reduxApi.reducers);
const finalCreateStore = applyMiddleware(thunk)(createStore);
const store = finalCreateStore(reducer);
```
This is a very bad idea. `store` this is not a getting current app state, but this is create a new store. And `function dispatch` change state in new store and not change state in current app state.

Can you add `getState` and `dispatch` as params to callback of `responseHandler`?

**Comment by lexich** [comment]
Hmmm you don't need create new store, you should reuse old one. `responseHandler` it's middleware for response, I'm not sure that `getState` and `dispatch` should be used in it. But if you really need, you have workaround

**Comment by pohodnya** [comment]
@lexich I'm sorry for my stupidity. I solved this problem, I define the handler in the same place where the store is created.
