### ISSUE TITLE
POST action replaces entire data array (until refresh)

### ISSUE THREAD

**Issue by tomsoderlund** [lexich/redux-api#182]
When I do a POST action, the entire array of data (`this.state.kittens.data` below) is replaced by the new post data. When I do a browser refresh, the data is restored. Why?

reduxApi config:

	export default reduxApi({

		kittens: {
			url: '/api/kittens/:id',
			crud: true,
			transformer: transformers.array,
			options: {
				headers: {
					'Accept': 'application/json',
					'Content-Type': 'application/json'
				}
			}
		}

	}).use('fetch', adapterFetch(fetch));

POST action:

	handleAdd (event) {
		const newKitten = {
			name: this.state.name,
		};
		this.props.dispatch(reduxApi.actions.kittens.post({}, { body: JSON.stringify(newKitten) }));
	}

JSX:

	<button onClick={this.handleAdd.bind(this)}>Add kitten</button>

**Comment by tomsoderlund** [comment]
I have similar issues with `put` and `delete` so it must be something basic I’m missing.

**Comment by tomsoderlund** [comment]
Test server: https://nextjs-express-mongoose.herokuapp.com

**Comment by lexich** [comment]
Every action update your state. By default it's replace strategy. 
Delete - returns nothing and list is replaced with nothing
Post - returns only new item and is replaced by it.
Refresh browser fetch all items and empty store is replaced by these items

**Comment by tomsoderlund** [comment]
So what’s the recommended way if I want to update state with:

old list + new POST = new list

?

**Comment by lexich** [comment]
yes :)

**Comment by tomsoderlund** [comment]
And how would I implement this?

With a transform in reduxApi config?

**Comment by tomsoderlund** [comment]
I think my issue is duplicate of #114.

A complete redux-api CRUD example would be nice. I’m rewriting my [nextjs-express-mongoose-crudify-boilerplate](https://github.com/tomsoderlund/nextjs-express-mongoose-crudify-boilerplate) to use redux-api, maybe that can serve as an example for others.

**Comment by tomsoderlund** [comment]
Not sure if this is the right approach, but I solved it with a custom `transformer`:

	transformer: function (data, prevData, action) {
		const actionMethod = _.get(action, 'request.params.method');
		switch (actionMethod) {
			case 'POST':
				return [...prevData, data];
				break;
			case 'PUT':
				return prevData.map(oldData => oldData._id === data._id ? data : oldData);
				break;
			case 'DELETE':
				return _(prevData).filter(oldData => oldData._id === data._id ? undefined : oldData).compact().value();
				break;
			default:
				return transformers.array.call(this, data, prevData, action);
		}
	},

Thankful for any suggestions on how to improve.

**Comment by lexich** [comment]
Good implementation 👍
