### ISSUE TITLE
Multiple dispatch via async all not working?

### ISSUE THREAD

**Issue by adamdonahue** [lexich/redux-api#185]
I'm trying to dispatch multiple actions as so:

```javascript
   search(term) {
      const x = dispatch(rest.actions.type1({ q: 'z' }));
      x.then(() => {
        dispatch(rest.actions.type2({ x: 'y' }));
      });
    },
```
or variations thereof.  I want to dispatch _two_ separate endpoints when search is executed, but I can't get this to work consistently.  I've tried various orders, etc., using force(), using sync() -- no matter what I do, either only one of the results returns, etc.  What's going on? Any ideas?

**Comment by lexich** [comment]
Hi @adamdonahue Pls show your configuration.
