### ISSUE TITLE
What are the "@" symbols for each bullet point for in DOCS.md?

### ISSUE THREAD

**Issue by YPCrumble** [lexich/redux-api#186]
Thanks for building this repo! I have a question regarding the documentation, for instance, this section:

- @description create endpoint
- @param **options** - configuration of rest-api endpoints
  - @type: Object
  - @default: {}
  - @example:

Are these "@" signs necessary? I was confused reading the documentation and as I continued reading it appears they are possibly redundant to the bullet points. If that's the case I'd be happy to make a PR to remove them, just trying to figure out if I'm missing something?

**Comment by lexich** [comment]
Hello @YPCrumble No "@" isn't necessary. If you can, pls make PR.
