### ISSUE TITLE
Is there a best practice for using this library to track the status of an XHR request?

### ISSUE THREAD

**Issue by YPCrumble** [lexich/redux-api#188]
Thanks for building this library! 

Let's say I have a button on my site that says "Fetch Posts" that passes an AJAX GET request to my server to fetch new posts. When the user clicks the button I want to disable it while the request is processing so they only GET the posts once. Once the request has finished, I want to display the new posts or error message, and re-enable the button.

I can see from [this section](https://github.com/lexich/redux-api#example) that there is a `loading` flag I should be able to access. Is this available by default on every redux-api endpoint?

The best example I can see is on the home page, but I'm confused as to the best way to access the `loading` flag. In the `render` section I see `const {entry, regions} = this.props;` and the app accesses `regions.loading`. However, I also see `const {dispatch} = this.props;` which is what I would have expected to be available as a prop. I don't see where `entry` and `regions` are passed to props. 

They are mentioned (but unused) in the state declaration - is that line then meant to be `const {entry, regions} = this.state;`?

I suspect if this were updated to a newer version of react-router we would pass `entry` and `regions` via props rather than state. I'd be happy to update the example if that's helpful? Let me know if any suggestions/feedback?

**Comment by lexich** [comment]
Hello @YPCrumble 
Every redux-api endpoint has unified structure. You can read about this in this section https://github.com/lexich/redux-api/blob/master/docs/DOCS.md#store-state-schema 

Redux-api is simple and light wrapper around redux and deliver only predefined actions and reducers which integrate in redux ecosystem. Access to data is according you way of injection it in your components
