### ISSUE TITLE
Response headers not passed

### ISSUE THREAD

**Issue by hpaul** [lexich/redux-api#19]
I face a problem for two days and realized that `redux-api` doesn't pass headers even when request was successfully or failed.

So when I dispatch this
![screen shot 2015-10-21 at 19 42 46](https://cloud.githubusercontent.com/assets/594424/10643613/6b41fe3c-782c-11e5-8ee1-fcbd00ce61ee.png)
Error it's just `Unexpected end of input`.

But I need to see response status code which is `401 Unauthorized` so I could dispatch an action to show a Login Modal
![screen shot 2015-10-21 at 19 47 38](https://cloud.githubusercontent.com/assets/594424/10643671/b6d7d22c-782c-11e5-80dd-99277289391a.png)

That's how `getDetails` is configured.
```javascript
  getDetails: {
    url: `${apiEndpoint}/user`,
    reducerName: 'account',

    options: {
      headers: headers,
    },

    prefetch: [
      attachAuthorization,
    ],

    validation: (data, cb) => {
      if (data.error) {
        cb(data);
      }

      cb();
    },
  },
```

**Comment by lexich** [comment]
You responce data is empty?

**Comment by hpaul** [comment]
Yep.

**Comment by lexich** [comment]
It's not a problem of redux api. It's a behaviour of XHR libraries, which don't like empty responce. As I know jquery.ajax do the same. You need add data to you response `{}`

**Comment by hpaul** [comment]
I thought at this first, and tryied this.
```javascript
fetch('******/user', { headers: { 'Authorization': 'Bearer ccd5d82b218a3624c6c199d3d8821645b7a0d16b27f5288147d6b1b20c0e7d56' } }).then(function (response) {
  console.log(response);
});
```
And returned this.
![screen shot 2015-10-21 at 20 43 20](https://cloud.githubusercontent.com/assets/594424/10645074/7ed12286-7834-11e5-9b17-763887d97c7d.png)

**Comment by lexich** [comment]
redux-api was designed with replacement backends. You problem is here https://github.com/lexich/redux-api/blob/master/src/adapters/fetch.js#L5 You can implement you own backend.

```js
const backend = function(fetch) {
  return function(url, opts) {
    return fetch(url, opts).then(.. you implementation ...);
  };
}
....
rest.init(backend(fetch));
```

**Comment by hpaul** [comment]
Oh, I really forgot about that, looked all around the code but didn't realized that.

Thank you.
