### ISSUE TITLE
Error: Windows Edge/Safari 7 doesn't make requests with `cache: true`

### ISSUE THREAD

**Issue by gormonn** [lexich/redux-api#192]
Windows Edge/Safari 7 doesn't make any requests with `cache: true`

**Comment by gormonn** [comment]
Lol what:
It's work in Chrome, Edge:
```shopProducts: {
        ...defaults,
        url: `${URL}/shop/products?id=:id`,
        cache: { expire: 360 },
        options: {
            credentials: 'include'
        }
    }```


It's work in Chrome, bot doesn't work in Edge:
```shopProducts: {
        ...defaults,
        url: `${URL}/shop/products?id=:id`,
        cache: { expire: 360 },
        options: {
            credentials: false
        }
    }```

**Comment by lexich** [comment]
Hello @gormonn 
First of all, the best way to describe URL is [rooturl](https://github.com/lexich/redux-api/blob/master/docs/DOCS.md#rooturl)

`options` - it's a config for [fetch](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch)

options, cache - is only abstraction not to update data in store

**Comment by gormonn** [comment]
Tnx for rooturl. I'm just saying, that request with prop `cache:true` work fine without cookies (credentials: false) in Chrome.
But behaves strange in Windows Edge.
For example. 

If we are trying to request in Chrome - everything is fine, we get data.
If we are trying to request in Edge - nothing happened, no errors, no action events, just nothing.
