### ISSUE TITLE
Configuring method on helpers

### ISSUE THREAD

**Issue by IronSean** [lexich/redux-api#198]
Is there a way to configure the `method` on `helpers`? 

You can use the `options: { method: 'post' }` configuration to set the method for all actions on an endpoint, and using `crud: true` will generate get/post/patch/put/delete with the appropriate methods, but if you want to customize your helpers for a nicer calling interface I can't figure out a way to specify it. In the following situation `post` will just use the `GET` method and duplicate `get`.

```javascript
export default {
  url: '/api/myApi/:id',
  helpers: {
    get(id: number) {
      return [{ id }, {}];
    },
    post(data) {
      return [{}, { body: JSON.stringify(data) }];
    },
  },
};
```

**Comment by lexich** [comment]
Hi @IronSean What do you want to configure?

**Comment by IronSean** [comment]
I want my `post` helper to use the the `method: 'POST'`.

**Comment by IronSean** [comment]
I figured it out. This didn't jump out at me in the docs, and it's adapter specific, but although the first object (labelled as urlParams in some examples) is processed to generate the url before being passed to the adapter, the second object just gets passed do the adapter where it can be processed. So custom handling can happen there for fields other than `body`, and in the case of the fetchAdapter fetch options can just be passed directly there.

So the following works:
```javascript
export default {
  url: '/api/myApi/:id',
  helpers: {
    get(id) {
      return [{ id }, {}];
    },
    post(data) {
      return [{}, { body: JSON.stringify(data), method: 'post' }];
    },
    // Other methods here
  },
};
```
