### ISSUE TITLE
Can you pass body in a GET request?

### ISSUE THREAD

**Issue by EduardoAC** [lexich/redux-api#199]
Hi All,

I am looking to customise a bit the get request provide by the actions provide by the redux-api.

Do you know a way to pass body into the get request so it can be supported large parameters?

Thanks in advance

**Comment by lexich** [comment]
Hi @EduardoAC - body in GET request it's url parameters. `?body=${encodeURIComponent(data)}` is you solution

**Comment by bravomartin** [comment]
This is not related to the library. GET requests don't send a body.
If you want to pass large parameters, you will need to use POST.

**Comment by EduardoAC** [comment]
Well, @bravomartin this is a recommendation rather than an imposition you can find more [here](https://stackoverflow.com/questions/978061/http-get-with-request-body)

Second, I convince my BE colleague to do use `query parameters` instead.
