### ISSUE TITLE
How to access results from REST service?

### ISSUE THREAD

**Issue by tomsoderlund** [lexich/redux-api#200]
Can I somehow immediately access the results from the REST service?

E.g. the example:

`dispatch(rest.actions.entry({id: 1}));`

If my REST server returns the ID of the new entry, how can I use that in my frontend app?

**Comment by lexich** [comment]
Hi @temnoregg ```dispatch(rest.actions.entry({id: 1})).then((data) => ...)```

**Comment by tomsoderlund** [comment]
Thank you @lexich! So simple...

**Comment by lexich** [comment]
@tomsoderlund I don't understand problem, may be you need to save this ID in another place. Can you show your case in details
