### ISSUE TITLE
Source map includes reserved identifier

### ISSUE THREAD

**Issue by jermspeaks** [lexich/redux-api#24]
In the source map file, it's reading `let values = []`, which is throwing a syntax error on Firefox as let is a reserved identifier.

In the `dist/redux-api.js` file, we see the following example on [line 1555](https://github.com/lexich/redux-api/blob/master/dist/redux-api.js#L1555).

```js
var values = [];
```

However, the source map file `dist/redux-api.js.map`, shows the following (which is all on one line).

```js
let values = [];\n\n
```

This is part of the [qs](https://github.com/hapijs/qs/issues) library, so I think webpack is incorrectly  creating an erroneous source map with this external library dependency.

If I get it to work, I'll send a PR. In the mean time, if anyone has any suggestion, or a fix, please pass it along.

**Comment by lexich** [comment]
I solve this problem with custom test in we pack config, https://github.com/lexich/redux-api/blob/master/webpack.config.js#L27
But I think you are right, code must works without workarounds
