### ISSUE TITLE
Many actions for one reducer?

### ISSUE THREAD

**Issue by mattapperson** [lexich/redux-api#3]
One issue I still have with this project is that in many cases I have many actions for data set (add user, edit user, remove user for example) how does one get all that into a single reducer?

**Comment by lexich** [comment]
It's pretty simple
`rest.actions.user({id:1},{method: "post"})` and other case like this way

**Comment by mattapperson** [comment]
As a default thats fine, but perhaps there could be a config option to override. in this way we could have
~~~
rest.actions.createUser({id:1});
~~~

Would a PR for this be acceptable?

**Comment by lexich** [comment]
I don't understand problem.
```js
const rest = reduxApi({
  createUser: {
    url: "/api/v1/user/:id",
    options: {
      method: "post"
    }
}
```

**Comment by mattapperson** [comment]
For example, without my PR, the following results in 3 reducers, when all we really want is one:

```js
const rest = reduxApi({
  getUser: {
    url: "/api/v1/user/:id",
  }
  createUser: {
    url: "/api/v1/user/:id",
    options: {
      method: "post"
    },
   updateUser: {
    url: "/api/v1/user/:id",
    options: {
      method: "post"
    }
}
```

**Comment by lexich** [comment]
```
const rest = reduxApi({
  user: {
    url: "/api/v1/user/:id",
  }
});
rest.actions.user(
  createUser: {
    
      method: "put"
    },
   updateUser: {
    url: "/api/v1/user/:id",
    options: {
      method: "post"
    }
}
```

**Comment by mattapperson** [comment]
Don't you think thats a bit messy?

**Comment by lexich** [comment]
Up

**Comment by mattapperson** [comment]
IMHO you should not need to put that kind of stuff (http methods) in your components. Also this assumes the endpoint remains the same. Yes you can then also include the URL, but at some point your almost redefining the API for the action every time you use it.

**Comment by lexich** [comment]
You right, but 'reducerName' seems bit complicated... Any way i will have access to computer only next week and we have time to imagine the best api for this case.

**Comment by lexich** [comment]
https://github.com/lexich/redux-api/pull/5
