### ISSUE TITLE
async helper does not pass data.

### ISSUE THREAD

**Issue by fusionstrings** [lexich/redux-api#33]
First of all thanks a lot for this wonderful library
I am trying out following snippets
```js
    async() {
        const {dispatch} = this;
        return (cb)=> {
          dispatch(rest.actions.logger((err)=> {
            const args = [{id: 1, name: "admin"}];
            cb(err, args);
          }));
        };
      }
```

and 

```js
async(dispatch, 
  (cb)=> rest.actions.test(cb),
  rest.actions.test2
).then((data)=> async(rest.actions.test3));
```

in both the cases I am not able to get `data` passed to next `then` block.

`data` is always undefined, I presume it should be fetched data. 
In my case my one entry depends on few other end points so I need to ensure values are there.

**Comment by lexich** [comment]
https://github.com/lexich/redux-api/blob/master/test/redux_spec.js#L41 it's the test suite of second case and here all looks ok

Can you show full example of you code?

**Comment by fusionstrings** [comment]
yup I understand that, infact I'd had a look on those tests. These tests help me so far to build my app but stuck on async.  Following is snippet what I am using.
 
```js

import reduxApi, { async } from "redux-api";

import servicesActions from './../actions/services.js';

export function hydrateState(){
  return (dispatch, getState) => {
    reduxApi.async(dispatch, servicesActions.myApp.productClasses).then(function (data) {
      console.log(data); // logs undefined
      
      console.log(getState().services.myApp.productClasses); // logs correct data
    })
  }
}
```

**Comment by lexich** [comment]
Can you show realization `servicesActions.myApp.productClasses`. 
This action must shoul realize interface looks like this.
```js
productClasses = (cb)=> {
  const error = "Error or null";
  const data = "Result data";
  cb(error, data);
}
```
As I understand you didn't use generated actions from redux-api, otherwise I should be able to help you, if you give me more information.

**Comment by fusionstrings** [comment]
Thanks a lot for your response. I apologize for not providing full code.
I am using actions from redux API, although I've imported in different module.
following is full code (assuming everything is in same folder).

````js
//action.js
import reduxApi, { async } from "redux-api";

import servicesActions from './actions-services.js';

export function hydrateState(){
  return (dispatch, getState) => {
    reduxApi.async(dispatch, servicesActions.myApp.productClasses).then(function (data) {
      console.log(data); // logs undefined
      
      console.log(getState().services.myApp.productClasses); // logs correct data
    })
  }
}

//actions-services.js

import {actions} from './api.js';

export default actions;

//api.js

import {combineReducers} from 'redux';
import myApp from './myApp-api.js';

export const reducers = combineReducers({
  myApp: combineReducers(myApp.reducers)
});

export const actions = {
  myApp: myApp.actions
};

//myApp-api.js

import reduxApi from 'redux-api';
import fetch from 'isomorphic-fetch';
import adapterFetch from 'redux-api/lib/adapters/fetch.js';

const URL = '/rest';

export default reduxApi({
  productClasses: {
    url: `${URL}/productclasses`
  }
}).init(adapterFetch(fetch), false);

```

**Comment by lexich** [comment]
I don't know what is the problem. I wrote the test https://github.com/lexich/redux-api/blob/master/test/redux_spec.js#L46 and it's not reproduce you situation.
Can you write crashing test?

**Comment by fusionstrings** [comment]
That's alright, thanks a lot for help :). Once again I can't thank you enough for this library.
