### ISSUE TITLE
Change redux state without actual API call.

### ISSUE THREAD

**Issue by istinspring** [lexich/redux-api#34]
Hello, first of all, this lib is really great time saver, hope you'll continue development.

Problem:

I store session data in cookes so if i reload the page state could be restored. It's kinda trivial if i use pure Redux, but i can not figure out if it's possible via redux-api.

```
    const authData = Cookies.getJSON(AUTH_COOKIE_PATH);
    if (authData !== undefined) {
      this.props.dispatch(...? how dispatch success action to set store with data 'authData' ?...);
    }
```

**Comment by lexich** [comment]
Tnx for good words.
As I understand you can use ‘postfetch‘ option https://github.com/lexich/redux-api/blob/master/README.md#postfetch 
Also you can write redux reducer and catch success event
```js
const rest = reduxApi({
test: "/tesr"
});

rest.events.test.actionSuccess // you can catch this event in you own reducer

```

**Comment by istinspring** [comment]
thanks! actually i did it like

```
    this.props.dispatch({
      type: auth.events.login.actionSuccess,
      syncing: false, data
    });  // where data is Cookies.getJSON(AUTH_COOKIE_PATH)
```

Really great lib! I'm able to keep my code base a way more smaller now using your lib. Less things to worry, redux-api doing all required stuff for me.

**Comment by lexich** [comment]
@istinspring I think the best way to use custom reducer and don't make workaround over 'redux-api'
```js
// reducer
export default function tokenReducer(state = Cookies.getJSON(AUTH_COOKIE_PATH), action) {
  switch(action.type) {
    case auth.events.login.actionSuccess:
      Cookies.setJSON(AUTH_COOKIE_PATH, state);
      return state;
    default:
      return state;
  }
}
```
