### ISSUE TITLE
How to get the pathvars used on a request?

### ISSUE THREAD

**Issue by andrefgneves** [lexich/redux-api#36]
Hi,

is there a way to get the `pathvars` used on a request?
For example, if I do `api.actions.product({ 'sku': 123 })` I want to be able to know what sku was used when the reducer function is invoked (the actionFetch). Right now I only get `{ syncing: false }`.

Or maybe I'm not using this right.

**Comment by lexich** [comment]
At this moment, unfortunately,  this information Don't pass to reducer directly. But you can write custom adapter and add this information in it.
```js
ReduxApi(...).use("fetch", (url, opt)=>{
    fetch(url, opt).then().then((data)=>{
        return {...data, url,  opt };
    });
})
```

**Comment by lexich** [comment]
close with #37
