### ISSUE TITLE
Recommended method for handling paging?

### ISSUE THREAD

**Issue by bitdivision** [lexich/redux-api#38]
Thanks for the great work on this library!

I'm attempting to use it with an API supporting paging but I don't see any information about how to extend the data in the store. 

For example, fetching page 1, and then page 2 would replace page 1 with page 2...

Is there an obvious way around this that I'm missing?

Thanks

**Comment by lexich** [comment]
Hello, thx for you words.

For pagination you don't need something special
```js
const rest = reduxApi({
  test: "/get/data"
});

....
dispatch(rest.actions.test({ page: 1 })  // /get/data?page=1
dispatch(rest.actions.test({ page: 2 })  // /get/data?page=2
```

And your state would be update according page param. Maybe you have more complex case?

**Comment by bitdivision** [comment]
Sure, but in my case that seems to replace the state in the store... I'm using 'start' and 'limit' instead of 'page' but I can't see that being an issue.

So after /get/data?start=0&limit=10 the 'test' store has 10 entries in data for example.
Then I do /get/data?start=10&limit=10 and 'test' store still has 10 entries in data, but all the data from page 1 has gone.

I'm wondering if there's an easy way to do caching on those pages, or is it simply catch a success action and move the data into a caching store?

**Comment by lexich** [comment]
You can write you own reducer and catch success events
```js
// reducer
const initialState = [];
export default function pagingReducer(state = initialState, action) {
  switch(action.type) {
    case rest.events.test.actionSuccess:
      return state.concat(action.data); // Here should be you own implementation caching
    default:
      return state;
  }
}
```
also you can use request param from PR #37 for create your own cache

**Comment by lexich** [comment]
Also you can use https://github.com/lexich/redux-api#virtual in this case, if you don't need state for current reducer

**Comment by bitdivision** [comment]
Okay, thanks very much for the quick replies.

I think I'll probably end up doing something with normalizr, similar to the [real-world example](https://github.com/rackt/redux/blob/master/examples/real-world/reducers/paginate.js) in redux. 

Thanks again.

**Comment by ifdion** [comment]
V vs SC an NFL Cy ban f f jdnya vice-versa Redford e were g no Jay on h

**Comment by lexich** [comment]
@ifdion WAT?

**Comment by ifdion** [comment]
Hi @lexich, apologize for previous comment.  Must be either my pocket or my 4 year old. Great redux plugin!
