### ISSUE TITLE
restApi.use('fetch', adapterFetch(fetch)) is required

### ISSUE THREAD

**Issue by pcarion** [lexich/redux-api#45]
Hi,
The documentation could be more explicit about the fact that the application MUST call `restApi.use('fetch', adapterFetch(fetch))` - if you don't you get an error like can't call apply on undefined.

Your root index.js should also reexport the `adapterFetch` function otherwise the only way to get to it is to put the entire path which is somewhat weird: `import adapterFetch from 'redux-api/lib/adapters/fetch';`

PS: so far, I really like the philosophy behind your API and I like the fact that you build the reducers automatically.

**Comment by lexich** [comment]
Thank you for feedback. I understood that documentation isn't good and I'm going to improve it and of course your comment will be included.
