### ISSUE TITLE
Caching?

### ISSUE THREAD

**Issue by GertjanJ** [lexich/redux-api#52]
Hi,

Trying it out for a while now and it works great!
The only issue I got with it is that there's no caching functionality?
Is it possible to add this functionality in the near future?
Thanks again!

**Comment by lexich** [comment]
Hi. You can use [sync](https://github.com/lexich/redux-api/blob/master/DOCS.md#syncurlparams-params-callback]) method for caching request.

```js
dispatch(rest.action.test()); // GET /api/test
dispatch(rest.action.test()); // GET /api/test

dispatch(rest.action.test.sync()); // if data was received there is no call to endpoint otherwise only one call
```

**Comment by GertjanJ** [comment]
Thanks!
