### ISSUE TITLE
Merging state with ImmutableJS

### ISSUE THREAD

**Issue by GertjanJ** [lexich/redux-api#53]
Hi!

When returning the data I would like the data to be merged into the immutable state. 
I'd like to do something like this: state.getIn(['api', 'settings', 'data'])  

Instead the reducer is initialized with a normal js object and the immutable data is passed to that object. This breaks my immutable chain. 

Api setup
<img width="263" alt="screen shot 2016-02-15 at 15 05 42" src="https://cloud.githubusercontent.com/assets/3602268/13050738/a3f693ee-d3f5-11e5-92e5-58d0a6c15476.png">

Redux devtools:
<img width="171" alt="screen shot 2016-02-15 at 15 04 28" src="https://cloud.githubusercontent.com/assets/3602268/13050705/743cfe90-d3f5-11e5-9b00-c052ffe3b791.png">

Or is there some other way that I missed to achieve this?

**Comment by lexich** [comment]
It's not big problem. If you use react-redux.
```js
function select(state) {
  return {
    settings: state.settings.data
  };
}
connect(select)(Component);
```
And now in component you can use immutableJS api.

**Comment by lexich** [comment]
Also in this sample you should modify your code.
```js
const api = reduxApi({
   settings: "/settings.json"
   //....other stuff
});

// https://github.com/lexich/redux-api/blob/master/DOCS.md#rooturl
api.use("rootUrl", "http://localhost:3000");
```

**Comment by osiloke** [comment]
Sorry for bringing this back to life, but did you mean that you want the whole state to be an immutable object? I think the best way would be to make your api endpoints virtual, [https://github.com/lexich/redux-api/blob/master/DOCS.md#virtual](url), and then handle the actions in your own custom reducer. 
What the author suggests is to just select the data which works but i'm not sure if thats what you wanted.

**Comment by lexich** [comment]
@osiloke redux-api has his own structure of state and it's use plain object. And, I don't understand purpose, but if it's necessary, you suggestion is true :)

**Comment by GertjanJ** [comment]
True @osiloke, thats what I meant. I read that redux performs better if the whole state is immutable?

**Comment by lexich** [comment]
Redux doesn't work if you mutate state. Inner state of redux-api updates without mutation. And I don't see reason use immutable-js for save Ajax data-response. Immutable-js may be convinient in pure (external) reducers where you change state "manually". Of cause you  can catch redux-api events and update external state

**Comment by osiloke** [comment]
@GertjanJ, i've also read somewhere that it does not provide much performance gain in small apps though. I think @lexich explanation is adequate
