### ISSUE TITLE
delete action fails

### ISSUE THREAD

**Issue by invisiblemachine** [lexich/redux-api#54]
while using the following code, i can successfully delete something from my api, but redux-api gives me a projectsDelete_fail action. apologies but i don't see anything in the docs about deletes being different.

`projectsDelete: {
  	helpers: {
  		byId(id) {
  			return [{id: id}];
  		}
  	},
  	options: {
  		method: 'delete'
  	},
		postfetch: [
			function({ dispatch, actions }) {
				dispatch(actions.projectsGet());
			}
		],
		url: 'projects/:id',
  }`

**Comment by invisiblemachine** [comment]
ah now that i asked my backend dev to add a nonsense response, it works, so it would be nice if it could not fail if no response is given for deletes

**Comment by lexich** [comment]
I think that you problem is that you delete response is empty. And if it's empty, `fetch` thinks that it's error. You should return something in this response and it fix your porblem.

**Comment by invisiblemachine** [comment]
yep, thanks
