### ISSUE TITLE
prevData been passed to transformer is always empty

### ISSUE THREAD

**Issue by osiloke** [lexich/redux-api#55]
For example, in a file api.js
```
export default reduxApi({
playback: {
    url: `${API_URL}/store/crums`,
    options: options,
    transformer: function(data, prevData, action){ 
      //prevData is retrieved from the stat as state.playback instead of state.api.playback
   }
  });
```
The state is stored as 
```
{
 api:{
    playback: 
       data: [],
      ...
  }
}
```
Redux api assumes the state is the following according to this line in the code, https://github.com/lexich/redux-api/blob/master/src/actionFn.js#L101
```
{ 
    playback: 
       data: [],
      ... 
}
```
Also, wouldn't it be better to just allow the whole getState() like you do in the `options` method.

**Comment by lexich** [comment]
I don't understand why you state have `api`? When you define endpoint `playback` your store look like this
```js
{ playback: { data: [] ... } }
```

**Comment by osiloke** [comment]
nope, my store looks like the following. The only difference with the api examples in this repos is that i'm exporting a module, ah maybe i should be exporting a var?
```
{
 api:{
    playback: {
       data: [],
      ...
   }
  }
}
```

**Comment by osiloke** [comment]
it was obvious, i was doing this
```
import _api from "../api";
_api.use("fetch", adapterFetch(fetch));
const api = combineReducers(_api.reducers)
export default combineReducers({ 
	api
})
```
Sorry for bothering

**Comment by jakeaaron** [comment]
I'm having the same exact issue.

I have an api reducer as well as such:

```javascript
export default combineReducers({
	plans: combineReducers(plansAPI.reducers),
	users,
	search,
	friends,
	readingPlans,
})
```
where `plansAPI` is the redux-api endpoint

and then I'm importing that into the main reducer.

can you explain how you structured it correctly?

My `prevData` is `undefined` in my plansAPI tranformers
