### ISSUE TITLE
Chained requests

### ISSUE THREAD

**Issue by hashwin** [lexich/redux-api#58]
I'm trying to get a chain of requests going, each of which has to complete before the next one fires.
Looking at the docs here: https://github.com/lexich/redux-api/blob/master/DOCS.md, it looks like the intended use is as follows:
```
async(
  dispatch, () => rest.actions.car.delete(carId)
).then((data)=> {
  debugger
  async(rest.actions.invoice({ id: this.props.invoice.data.id }))
});
```

Unfortunately that debugger is never hit, the then function is never called.
Any idea what's going on here?

**Comment by lexich** [comment]
redux-api uses async actions
```js
async(
  dispatch, (cb) => rest.actions.car.delete(carId, cb)
).then((data)=> {
  debugger
  async(dispatch, (cb)=> rest.actions.invoice({ id: this.props.invoice.data.id }, cb));
});
```

**Comment by hashwin** [comment]
Thanks, that did the trick.
