### ISSUE TITLE
How do you chain dispatch requests with redux-api

### ISSUE THREAD

**Issue by mrbinky3000** [lexich/redux-api#61]
Before using redux-api, calls to `dispatch()` in a component returned a promise.  Now they return "undefined."   I can no longer chain actions, like `dispatch(...).then(...do stuff...);`

**Comment by lexich** [comment]
At this moment, only using [async tool](https://github.com/lexich/redux-api/blob/master/DOCS.md#async). But I think that it's possible add behaviour ```dispatch(...).then(...do stuff...);``` Now redux allow to do this.

**Comment by mrbinky3000** [comment]
dispatch() does not return a promise.  So you can't do .then() directly on it.  However, your async tool does.  Thank you.  I think you can close this issue out.  I'm satisfied.
