### ISSUE TITLE
is there a way to modify the url in a helper?

### ISSUE THREAD

**Issue by modosc** [lexich/redux-api#62]
consider an api like:

```
GET /users
GET /users/:id
POST /users/:id/invalidate
POST /users/:id/forgot_password
```

i've managed to emulate this behavior like so:

```
user: {
  url: `/users/:id/(:method)`,
  virtual: true,
  helpers: {
    invalidate({id}) {
     return [{id: id, method: 'invalidate'}, { method: "post"} ];
    },
    forgot_password({id}) {
     return [{id: id, method: 'forgot_password'}, { method: "post"} ];
    }
  }
}
```

but this doesn't work if i need to also access the resource (ie, without virtual=true). is there a better way to do this (or would you be open to a pr to add this functionality?)

**Comment by lexich** [comment]
I don't understand problem with access to resource. [helpers](https://github.com/lexich/redux-api/blob/master/DOCS.md#helpers) 
```js
invalidate({id}) {
   const state = this.getState(); // access to store
   return [{id: id, method: 'invalidate'}, { method: "post"} ];
},
```
Can you write about your problems more detail?

**Comment by modosc** [comment]
sure - if i'm understanding correctly helpers just allow me to modify the url params and request options. i can't modify the actual url though - in my example above i worked around it but i'd prefer to be able to do something clearer like:
```
user: {
  url: `/users/:id`,
  helpers: {
    invalidate:
      // mabye url is passed in and modified inline?
      url: function(url) { return url + '/invalidate' },
      // or maybe the default is just to join the new fragment with the existing url?
      url: '/invalidate',
      options: { method: "post"}
    }
  }
}
```

i know i can add a new route like this:
```
user_invalidate: { 
  url: `/users/:id/invalidate`,
  options: { method: 'post' },
}
```
but then i lose any pre/postfetch callbacks i might have setup in the original `user` resource. 

does that make sense? i guess this is a special case of nesting resources so i'm not sure how you'd really want to deal with it.

**Comment by lexich** [comment]
I think about it, I haven't mind about this. But I think that you walkaround is more right way, than new DSL. And what problems do you have with your current solution?

**Comment by hsingh23** [comment]
I'm also trying to deal with the same problem. An ability to change the url in a helper would be ideal
