### ISSUE TITLE
DELETE does not trigger postfetch

### ISSUE THREAD

**Issue by calvinnwq** [lexich/redux-api#63]
When a DELETE is done successfully, it does not trigger the postfetch. The response is:

```
Response: {
    ...
    ok:true
    status:204
    statusText:"No Content"
    ...
}
```

In #54 you mentioned that delete response should not be empty, but returning a 204 means not returning any response content, which is still valid.

**Comment by lexich** [comment]
It's not problem of my lib, but it's problem XMLHttpRequest and fetch. They return error to promise. But you can realize own [adapter](https://github.com/lexich/redux-api/blob/master/DOCS.md#fetch) or may be explain how to solve this problem.

**Comment by lexich** [comment]
And [code](https://github.com/lexich/redux-api/blob/master/src/adapters/fetch.js) of default fetch adapter is pretty simple.

**Comment by calvinnwq** [comment]
The problem that I discovered lies in trying to do `response.json()` on an empty response. This will cause the promise to throw `SyntaxError: Unexpected end of input`. Same goes with XMLHttpRequest. I had to rewrite the adapter to handle 204.

**Comment by wvengen** [comment]
Perhaps it's is too straightforward to post, but you could use this as a fetch adapter:

```js
function adapterFetch(fetch) {
  return function(url, options) {
    return fetch(url, options).then((resp) => {
      if (resp.status !== 204) {
        return resp.json();
      }
      // @todo handle errors
    });
  }
}
```
