### ISSUE TITLE
Sync with different query parameters

### ISSUE THREAD

**Issue by wvengen** [lexich/redux-api#70]
I'm accessing an index endpoint with search parameters, and trigger a `sync()` whenever a different filter is selected on the client-side. It appears that redux-api's `sync()` never calls out to the server when it's already been loaded, even when the query parameters are different.

```javascript
const rest = reduxApi({
  articles: {
    url: '/api/v1/articles',
    transformer: transformers.array,
  }
});

class Foo extends React.Component {  

  componentDidMount() {
    this.props.dispatch(rest.actions.articles.sync({category_id: 1}));
  }

  // ...

  _onClick(category_id) {
    this.props.dispatch(rest.actions.articles.sync({category_id: category_id}));
  }

}

// connect ...
```

This always keeps the items in the store with `category_id=1`, even if a `sync({category_id: 2})` is called later.

Setting the article's `sync` key makes it work though:
```javascript
  _onClick(category_id) {
    this.props.articles.sync = false; // hack
    this.props.dispatch(rest.actions.articles.sync({category_id: category_id}));
  }
```

I wonder, wouldn't it be better if `sync()` returned the data directly (without another http roundtrip) only if the parameters are equal?

**Comment by lexich** [comment]
At this moment your can use 'reset' method, because store should be immutable or use latest API 'reducers' for external modify store via event. 
In future,  I probably add more simple API to reset sync flag. 
Tnx for your feedback.

**Comment by lexich** [comment]
https://github.com/lexich/redux-api/commit/e80c3402bcbfa6c6daa29855b3d798f394f237ca
Now you can update to version 0.9.4 and use `.reset("sync")` functionality.

**Comment by wvengen** [comment]
Thanks!!
