### ISSUE TITLE
When reducerName is set, transformer does not receive "prevData"

### ISSUE THREAD

**Issue by lordi** [lexich/redux-api#71]
The line in question is this:

https://github.com/lexich/redux-api/blob/17b44bb40840a9f372d07cd1ddc6e13d5efb0841/src/actionFn.js#L126

Here "name" is the original name, not reducerName.

**Comment by lexich** [comment]
Yes, It's bug. If you want, you can fix it with PR, otherwise I'm going to fix it next week
