### ISSUE TITLE
shared action between reducer mutates data in transformer?

### ISSUE THREAD

**Issue by jeffreygnatek** [lexich/redux-api#72]
thanks for the great library, i am experiencing a bug that while entirely could be my own fault, seems to happen in the transformer, i'll try to explain without detailed code below,

reducer 1 listens for api.events.categories.actionSuccess and puts that data into an object
reducer 2 listens for api.events.categories.actionSuccess and puts that data into an object
reducer 2 also changes the data to toggle on certain categories that the user has chosen (comes from different api call).

the issue is that in the transformer i wrote i can see the data from reducer 2 mutating what the transformer is returning, which seems strange. so reducer 1 gets the mutated data from reducer two via the action.data in the api.events.categories. 

i'm curious if anyone has experienced this or something like it

**Comment by lexich** [comment]
Thx for you issue. But some code will improve my understanding of problem.

**Comment by jeffreygnatek** [comment]
let me try to put something together that isn't the entire repo, thanks
