### ISSUE TITLE
How to use the crud helper functions

### ISSUE THREAD

**Issue by andreas-koch** [lexich/redux-api#75]
Redux-api really makes using REST APIs easy. 
I read the documentation for the helper functions. So far I got them working only via dispatch like: 
```
 dispatch(rest.actions.group({}, {
      body: JSON.stringify({ name: this.state.name})
    }));
```
The following does not issue a REST request: 
`rest.actions.groups.get({ id: this.props.params.groupId})`
How are the helper functions supposed to be used.

Thanks,
Andreas

**Comment by lexich** [comment]
Pls write you code where you describe you `group` endpoint and I help you to rewrite you code.

**Comment by andreas-koch** [comment]
const baseAPI = "http://localhost:6050";
group: {
    url: baseAPI+'/groups',
    options:{
      method: "post",
      headers: {
        "Content-Type": "application/json",
        "Accept": "application/json"
      }
    }
 }
Also, how can I check for success or errors.

**Comment by lexich** [comment]
At First, this code you can transform to next, more conventional
```js
reduxApi({
   group: {
     url: '/groups',
     options: { method: "post" }
   }
})
.use("rootUrl", "http://localhost:6050")
.use("options", {
  headers: {
    "Content-Type": "application/json",
    "Accept": "application/json"
  }
})
```

Success or Errors you can check using params in store https://github.com/lexich/redux-api/blob/master/DOCS.md#store-state-schema

or you can catch redux-api events https://github.com/lexich/redux-api/blob/master/DOCS.md#events

It depends from your needs.

**Comment by andreas-koch** [comment]
Thank's that helped.
