### ISSUE TITLE
Axios adapter

### ISSUE THREAD

**Issue by astrauka** [lexich/redux-api#80]
Hello, I would like to use https://github.com/mzabriskie/axios as a fetch adapter but cannot find examples to do it. Could you help me on this?

**Comment by lexich** [comment]
Sample of adapter you can see [here](https://github.com/lexich/redux-api/blob/master/src/adapters/fetch.js).

In you case code will be looks like this...
```js
axiosAdapter = function (axios) {
   return function(url, opts) {
      return axios({
         ...opts, url
      });
   };
}
```

**Comment by astrauka** [comment]
Thank you @lexich .
I have also found that one can use default adapter, just need to pass data in `{ data: ... }` key
