### ISSUE TITLE
Handling errors with helpers

### ISSUE THREAD

**Issue by shir** [lexich/redux-api#82]
I have next api:

```js
export default reduxApi({
  project: {
    url: `${URL}/projects/(:id)`,
    options: options,
    helpers: {
      create(data, callback) {
        return [{}, {method: 'POST', ...data}, callback]
      }
    }
  }
}).use("fetch", adapterFetch(fetch));
```

And call it next way:
```js
dispatch(forgeApi.actions.project.create({
      project: {
        name:        values.name,
        description: values.description,
        startDate:   values.startDate,
        endDate:     values.endDate,
      }
    }, (error, data) => {
      console.log("error: ", error)
      console.log("data: ", data)
      return Promise.resolve(data)
    }))
```
I have response 422 from server (as it should be with test data) but in callback I have `null` error and data with parsed json from server. It's ok to have parsed json but I wonder why error is empty. In this case I don't now if request was success or not and how I should interpret data from response as created object or as error description.

**Comment by lexich** [comment]
I think that your error here.
```
export default reduxApi({
  project: {
    url: `${URL}/projects/(:id)`,
    options: options,
    helpers: {
      create(data) { // Your don't need callback
        return [{}, {method: 'POST', ...data}] //Your don't need callback
      }
    }
  }
}).use("fetch", adapterFetch(fetch));
```

**Comment by shir** [comment]
@lexich do you mean I have to get error from state? I've just tried to remove callback from helper and tried to get error from state but get same values: error is null and data are parsed json.

**Comment by lexich** [comment]
``` {method: 'POST', body }``` is parameter of `fetch`.  https://developers.google.com/web/updates/2015/03/introduction-to-fetch

```js
export default reduxApi({
  project: {
    url: `${URL}/projects/(:id)`,
    options: options,
    helpers: {
      create(data) { // Your don't need callback
        const body = JSON.stringify(data);
        return [{}, {method: 'POST', body }]
      }
    }
  }
}).use("fetch", adapterFetch(fetch));
```

**Comment by shir** [comment]
I don't have issues with making request. Data are passed as expected. I see it in browser's log and on server log. I have expected response with status 422 and json with description of error. But redux-api doesn't return me this error. Redux-api says that the request was success and that there is no any errors.  I see only in logs if there was an error or not, but can't get this info from redux-api.

**Comment by lexich** [comment]
Redux-api shouldn't return error. It updates state. If response fails, state updates with error in error field.
https://github.com/lexich/redux-api/blob/master/DOCS.md#store-state-schema

**Comment by shir** [comment]
> If response fails, state updates with error in error field
But it doesn't update! That's the issue! The error field in state states null.

**Comment by lexich** [comment]
You can write you own adapter https://github.com/lexich/redux-api/blob/master/src/adapters/fetch.js and debug it. Unfortunately I can't say what happens in you server/client.
