### ISSUE TITLE
Handling errors like 'unauthorized' globally

### ISSUE THREAD

**Issue by laxplaer** [lexich/redux-api#84]
Hi, thank you for a great plugin. I was wondering if there is a nice way how to handle errors globally. For example if the cookie expiry I would love to see some global handling of unauthorised request in one spot. Event 'actionFail' seems too manual to put everywhere.

**Comment by wvengen** [comment]
You might find #78 a useful read, I'm currently [using](https://github.com/foodcoops/foodsoft-shop/blob/cf92664e42309ff4adcc1e6c71efb7f72bf4be97/src/store/store.js) a store listener to put errors in the state, which a notifier can handle.

**Comment by wvengen** [comment]
If you want to handle a specific http status differently, that's probably best done in a customized fetch adapter (e.g. [like this](https://github.com/foodcoops/foodsoft-shop/blob/cf92664e42309ff4adcc1e6c71efb7f72bf4be97/src/store/rest_fetch.js)).

**Comment by lexich** [comment]
@wvengen +1 good work.

**Comment by laxplaer** [comment]
Thank you for the answers.. I have implemented something similar like @wvengen was mentioning.. Tha actually work better in my scenario..
