### ISSUE TITLE
Allow to set qs options

### ISSUE THREAD

**Issue by wvengen** [lexich/redux-api#85]
APIs have different ways to work with array parameters, and [qs](https://github.com/ljharb/qs) (which is used by redux-api) allows one to [choose](https://github.com/ljharb/qs#stringifying) the array serialization method using the `arrayFormat` option.

Currently redux-api calls `qs` without any options, it would be useful to allow stringification options in [`urlTransform`](https://github.com/lexich/redux-api/blob/91c0f5a2ae62390233308d95a91bd1844c722a4a/src/urlTransform.js#L41). See, for example, request's [qsStringfyOptions](https://github.com/request/request#requestoptions-callback). Perhaps as part of `params`?

**Comment by lexich** [comment]
Good Idea, are you ready to make PR?
