### ISSUE TITLE
Vanilla version exposes inaccessible object name to global namespace

### ISSUE THREAD

**Issue by fedulovivan** [lexich/redux-api#87]
In a browser, if I'm loading module using just script tag, module could be accessed only via `window["redux-api"]`. Since "redux-api" is not a valid variable name.
`var ReduxApi = window["redux-api"];` solves.

**Comment by lexich** [comment]
Thx for your issue, I add information to Readme.md. Unfortunately there isn't simple way to rename global variable, because webpack generate code, which add compatibility with AMD, CMD and global sharing.
