### ISSUE TITLE
How to extend generated reducer with custom one? 

### ISSUE THREAD

**Issue by fedulovivan** [lexich/redux-api#88]
Hi! This is more a question rather than issue.
My scenario as follows. I have a store element, say 'rules', connected to rest backend via your module.
Initialization looks as:
```javascript
reduxApi = ReduxApi({
rules: {
crud: true,
url: "/api/rule",
transformer: data => _.indexBy(data, "id")
}
})
```
Later fetching is triggered as prescribed via
```
store.dispatch(reduxApi.actions.rules());
```
reducers extended with some custom ones via
```
_.extend(reduxApi.reducers, myReducers);
var store = Redux.createStore(Redux.combineReducers(reduxApi.reducers));
```

This approach works great unless I need to supply my custom reducers namely for **store.rules** object.
Say we need to delete some rule on server and upon receiving success response remove entry from local store.

In this case I have to dispatch two actions:

- reduxApi.actions.rules.delete()
- my custom one, lets call it deleteRuleFromLocalStoreAction()

So, I've stuck trying to understand what is the proper place for deleteRuleFromLocalStoreReducer reducer.

**Comment by lexich** [comment]
Hi. You should rename endpoint in redux-api or you reducer, because you rewrite redux-api reducer `rules` with your own. It's wrong.

**Comment by fedulovivan** [comment]
Thank for quick reply! Does it mean that I cannot define any custom reducers for the store elements handled by redux-api? Probably you assumed some another usage scenario when were creating this library. I'm very newbie in redux world, so probably I'm just misunderstanding something..

**Comment by lexich** [comment]
If you need update store which you defined with redux-api - you should use https://github.com/lexich/redux-api/blob/master/docs/DOCS.md#reducer

But in common case redux-API helps to avoid a lot of boilerplate code to write rest calls. On my mind redux-api store should be updated by backend, and client side updates like hacks

**Comment by fedulovivan** [comment]
My apologises for late feedback. Had a chance to try suggested solution. Reducer option is **exactly** what was needed. As I already mentioned above - the case for extending reducer is applying modifications on local store after changes were successfully saved. This also referred in different articles as 'pessimistic updates'. 
However, later I have faced with another issue. On receiving 200 response for delete request I observe following exception in console: 
<img width="1235" alt="screen shot 2016-06-20 at 22 34 56" src="https://cloud.githubusercontent.com/assets/752105/16207743/da98d99a-373f-11e6-9a68-abc4b8953eee.png">
<img width="646" alt="screen shot 2016-06-20 at 22 37 29" src="https://cloud.githubusercontent.com/assets/752105/16207777/0db4200a-3740-11e6-95e9-4b068234457a.png">
<img width="604" alt="screen shot 2016-06-20 at 22 39 09" src="https://cloud.githubusercontent.com/assets/752105/16207830/43344fde-3740-11e6-9a4b-736aeb587ac6.png">

**Comment by lexich** [comment]
You have empty response content. See #63

**Comment by fedulovivan** [comment]
I'm wondering if it possible not to apply server response onto store.. After fixing issue related to #63 I consequently faced with anther one:( For instance: delete operation now replies with empty object {} (or something like {status:"ok"}). And what I have - it overrides all store contents. It seems that your initial idea was to return truncated collection from server in such cases, right?

**Comment by lexich** [comment]
You should use [transformer](https://github.com/lexich/redux-api/blob/master/docs/DOCS.md#transformer). 
``` function customTransformer(data, prevData,{type, request}) ``` Type and request helps to identify what request you do and then using `prevData` construct new state.

**Comment by fedulovivan** [comment]
Indeed. My bad, I missed that prevData and current action are also supplied to transformer. Thanks again!
