### ISSUE TITLE
HTTP response codes not respected

### ISSUE THREAD

**Issue by georgewhewell** [lexich/redux-api#89]
my api:

    const api = reduxApi({
      auth: {
        url: '/auth/profile/',
      }})

my reducer:

    export default function auth (state = initialState, action) {
      console.log('Reducer action', action)
      switch (action.type) {
        case api.events.auth.actionSuccess: // user has own information about access
            console.log('SUCCESS')
          return { ...state, profile: action.data };
        case api.events.auth.actionFail:
            console.log('FAIL')
          return { ...state, token: null }
        default:
          return state
      }
    }

when server responds with 403, i get:

    Reducer action { type: '@@redux-api@auth',
      syncing: true,
      request: { pathvars: undefined, params: {} } }
    Reducer action { data: { detail: 'Invalid token.' },
      origData: { detail: 'Invalid token.' },
      type: '@@redux-api@auth_success',
      syncing: false,
      request: { pathvars: undefined, params: {} } }

**Comment by lexich** [comment]
Very strange result. I think that you problem is in adapte. https://github.com/lexich/redux-api/blob/master/docs/DOCS.md#fetch May be you should write custom adapter for you case. https://github.com/lexich/redux-api/blob/master/src/adapters/fetch.js

**Comment by georgewhewell** [comment]
ah yes, with this custom adaptor now I get `@@redux-api@auth_fail` when response code is error:

    function adapterFetchThrowErrors (fetch) {
      return function (url, opts) {
        return fetch(url, opts).then(
          (resp)=> {
            if (resp.status >= 400) {
              throw new Error({ status: resp.status, statusText: resp.statusText });
            }
            resp.status !== 204 ? resp.json() : {};
          });
      };
    }

I would have assumed this behaviour by default though. It seems like issue #82 is same thing.

Thanks for this great library! :)

**Comment by thenewguy** [comment]
Any chance of something like this becoming default?
