### ISSUE TITLE
Action is not getting dispatch and getState from props

### ISSUE THREAD

**Issue by dulichan** [lexich/redux-api#94]
Hi guys,
When I pass the `dispatch` and `getState` in a props using middleware - the redux-api doesn't seem to get the `dispatch` and `getState` from props.

Middleware code
```
const injectMiddleware = deps => ({ dispatch, getState }) => next => action =>
  next(typeof action === 'function'
    ? action({ ...deps, dispatch, getState })
    : action
  );
```

The code in react-api -

```
 return function (dispatch, getState) {
      var reducerName = meta.reducerName;

      var state = getState();
      var store = state[reducerName];
```

The above [function](https://github.com/lexich/redux-api/blob/master/src/actionFn.js#L99) doesn't receive two parameters but just one that contains all the dependencies. Below is what I changed the code to

```
return function (props) {
      var {dispatch, getState} = props;
      var reducerName = meta.reducerName;

      var state = getState();
      var store = state[reducerName];
```

**Comment by lexich** [comment]
Why do you use so strange middleware? It's the same as https://github.com/gaearon/redux-thunk/blob/master/src/index.js but with other composing of arguments @dulichan

**Comment by dulichan** [comment]
@lexich  I am using a stack called este [2] which uses this method to compose middleware [1]. I am wondering if there is a way to integrate thunks into this cause a lot of projects use thunks. 


[1] - https://github.com/este/este/blob/master/src/common/configureMiddleware.js#L12
[2] - https://github.com/este/este

**Comment by lexich** [comment]
@dulichan It's for you https://github.com/lexich/redux-api/blob/master/docs/DOCS.md#middlewareparser
