### ISSUE TITLE
Infinite Scroll

### ISSUE THREAD

**Issue by hashwin** [lexich/redux-api#95]
Hi @lexich , as always, great work with this library.

I am trying to implement infinite scroll, but the reducer doesn't seem to be running for the corresponding resource. Here's what I've set up, somehow the action success for that particular resource is never reached. It does run it for all other resources. Anything I'm doing wrong?

```
function indexOptions(resourceName) {
  return {
    url: `${URL}/${resourceName}/:collection`,
    options: { headers },
    transformer: transformers.array,
    reducer(state, action) {
      if(action.type === this.events[resourceName].actionSuccess) {
        // Never reached
        state.data = state.data.concat(action.data);
      }
      return state;
    }
  };
}

let options = {}
let models = ['test1', 'test2'];
models.forEach((resourceName) => {
  options[resourceName] = indexOptions(resourceName);
});

```

Thanks in advance!

**Comment by lexich** [comment]
I need detailed example of initialization this piece of code and how you use it. Anyway this piece of code contains error.

```js
function indexOptions(resourceName) {
  return {
    url: `${URL}/${resourceName}/:collection`,
    options: { headers },
    transformer: transformers.array,
    reducer(state, action) {
      if(action.type === this.events[resourceName].actionSuccess) {
        // Never reached
        state.data = state.data.concat(action.data);
      }
      return state;
    }
  };
}

const options = ["test1", "test2"].reduce((memo, resourceName)=> {
   memo[resourceName
   return memo;
), {});

reduxApi(options).init("rootUrl", URL);

let options = {}
let models = ['test1', 'test2'];
models.forEach((resourceName) => {
  options[resourceName] = indexOptions(resourceName);
});

```

**Comment by hashwin** [comment]
Hi @lexich , thanks for the quick reply.
I had only given the relevant portion of code. I call it normally in the app like:
```
dispatch(rest.actions.test1(params));
```
This works great when the data can just be replaced, but I would like to append the data.

If I run a console.log like this:
```
function indexOptions(resourceName) {
  return {
    url: `${URL}/${resourceName}/:collection`,
    options: { headers },
    transformer: transformers.array,
    reducer(state, action) {
      console.log(resourceName, action.type);
      if(action.type === this.events[resourceName].actionSuccess) {
        // Never reached
        state.data = state.data.concat(action.data);
      }
      return state;
    }
  };
}
```
This would give the result:
```
...
test2 @@redux-api@test1_fail
test1 @@redux-api@test2_fail
test2 @@redux-api@test1_success
test1 @@redux-api@test2_success
...
```
But would never give the required "test1 @@redux-api@test1_success"

**Comment by lexich** [comment]
First of all, redux use with immutable data, you can read about it in http://redux.js.org/docs/introduction/ThreePrinciples.html  

Second reducer function receive all action from system, and if you have @@redux-api@test1_success in log this means that you have initialization problem.

**Comment by lexich** [comment]
```js
return { ...state,  data: state.data.concat(action.data) }; // Error: you mustn't to mutate state
```

**Comment by hashwin** [comment]
If I can't append to the state, then how can I add the next page's data to the current data?

**Comment by wvengen** [comment]
`Array.concat` creates a copy that combines elements of both, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat), so in that respect https://github.com/lexich/redux-api/issues/95#issuecomment-236211071 looks fine to me. Or am I too missing something?

**Comment by lexich** [comment]
also if you don't use babel (why you don't do it) you can use follow construction.
```js
return Object.assign({}, state, { data: state.data.concat(action.data} });
```
resulting state will be with appending data. But this code is the same as in https://github.com/lexich/redux-api/issues/95#issuecomment-236211071

**Comment by lexich** [comment]
I forgot about right way to append data. You don't need reducer - it's very tricky functionality .

```js
{
   transformer(data,  prevData) {
      return prevData.concat(data); 
   }
}
```
