### ISSUE TITLE
Usage with redux-auth?

### ISSUE THREAD

**Issue by leon-wbr** [lexich/redux-api#96]
Hi, is it possible to use this with [redux-auth](https://github.com/lynndylanhurley/redux-auth) and if so, how? I suppose I would just need to call redux-auth's fetch function before the call and send the token with each request.

**Comment by lexich** [comment]
Redux-api it's only wrapper to redux. It uses the same actions and reduces, but one generate it for you. You can use redux-auth infrastructure to authentification and make other ajax calls with redux-api.

If your need sign each request (for example with Bearer token) your can look at this example https://github.com/lexich/redux-api/blob/master/docs/AuthorizationJWT.md but in your case you can get token from redux-auth state.

If you need example to your use case, can you give me some pieces of your code?
