### ISSUE TITLE
Error not set when failure occurs

### ISSUE THREAD

**Issue by mikeengland** [lexich/redux-api#97]
For any adapter I have tried, the error is set as an empty object in the state if a failure occurs - even though when debugging the reducer, the error is present in the action payload.

I changed the line `action: action.error` to `action: action.error.message` on my fork of redux-api and the error is then set correctly for any thrown errors.
https://github.com/mikeengland/redux-api/commit/a4b12bdf8868f94e58bf405e484c0951b3e8271a

**Comment by lexich** [comment]
I think that you fix problem in wrong place. I can't reproduce one, but I think that needed to start find bug in this lines https://github.com/lexich/redux-api/blob/master/src/actionFn.js#L158-L160 I'll be cool if you write test which reproduce problem

**Comment by mikeengland** [comment]
Sure, I will look at writing a test case. I looked at the error here, and in the reducer and i could log the error to the console. However, in the state the error was always an empty object.

**Comment by mikeengland** [comment]
Interestingly, even the test is failing for me (undefined is returned):

  1) reducerFn check:
`
      AssertionError: expected { Object (loading, data, ...) } to deeply equal { Object (loading, error, ...) }
      + expected - actual

       {
         "data": {
      -    "msg": "Hello"
      +    "msg": "Hello"
         }
      -  "error": [undefined]
      +  "error": "Error"
         "loading": false
         "syncing": false
       }`

**Comment by mikeengland** [comment]
I have found the reason this was not working. I am using a jQuery adapter like shown in the following issue: https://github.com/lexich/redux-api/issues/89 . However, the example code there throws an error if the return code is greater than 400. 

If instead of throwing an error you reject with an object containing the error details, then the errors are stored in the state as expected.

My working code:

```javascript
return new Promise(function (resolve, reject) {
            $.ajax({
                url: url,
                success: resolve,
                error: function (request, error) {
                    if (request.status >= 400 && !request.statusText.includes('Application abort request')) {
                        reject({
                            status: request.status,
                            statusText: request.statusText,
                            responseText: request.responseText,
                            responseJSON: request.responseJSON
                        });
                    } else {
                        resolve(request.status !== 204 ? request.json() : {});
                    }
                },
                failure: reject,
                ...opts
            })
        }
    );
```
