### ISSUE TITLE
403 response from server does not set error

### ISSUE THREAD

**Issue by thenewguy** [lexich/redux-api#99]
The provided fetch adapter does not seem to provide an error status on 403.

I've configured per docs:
```
// Redux-api
import reduxApi from "./rest";
import adapterFetch from "redux-api/lib/adapters/fetch";
require('es6-promise').polyfill();
import "isomorphic-fetch";

// Initialize react-api
reduxApi.use("fetch", adapterFetch(fetch));
```

This shows the fetch receives a 403 from the server:

<img width="640" alt="redux-api-403" src="https://cloud.githubusercontent.com/assets/77731/18022291/9204e83a-6bbb-11e6-922f-ca1bcd493132.png">

But the component does not get an error for this.  So I can only render an empty "no results" response instead of telling the user they do not have permission to view the requested results.

I know my error detection code is working because I can get it to show other errors.

I haven't found the culprit yet but I figured I would go ahead and raise the issue

**Comment by lexich** [comment]
@thenewguy try to update last version 0.9.10
